// Order preserves the legacy booking row-array contract throughout the API.
export const BOOKING_TABLE_FIELDS = [
  { name: 'booking_id', prop: 'id', type: 'STRING', mode: 'REQUIRED' },
  { name: 'customer_name', prop: 'customerName', type: 'STRING' },
  { name: 'phone', prop: 'phone', type: 'STRING' },
  { name: 'email', prop: 'email', type: 'STRING' },
  { name: 'branch_name', prop: 'branchName', type: 'STRING' },
  { name: 'service_name', prop: 'serviceName', type: 'STRING' },
  { name: 'therapist_name', prop: 'therapistName', type: 'STRING' },
  { name: 'date', prop: 'date', type: 'STRING' },
  { name: 'time', prop: 'time', type: 'STRING' },
  { name: 'payment_option', prop: 'paymentOption', type: 'STRING' },
  { name: 'paid_amount', prop: 'paidAmount', type: 'FLOAT64' },
  { name: 'total', prop: 'total', type: 'FLOAT64' },
  { name: 'duration_minutes', prop: 'durationMinutes', type: 'INT64' },
  { name: 'branch_address', prop: 'branchAddress', type: 'STRING' },
  { name: 'intake_notes', prop: 'intakeNotes', type: 'STRING' },
  { name: 'calendar_id', prop: 'calendarId', type: 'STRING' },
  { name: 'calendar_event_id', prop: 'calendarEventId', type: 'STRING' },
  { name: 'created_at', prop: 'createdAt', type: 'STRING' },
  { name: 'receipt_number', prop: 'receiptNumber', type: 'STRING' },
  { name: 'receipt_issued_at', prop: 'receiptIssuedAt', type: 'STRING' },
  { name: 'receipt_email_status', prop: 'receiptEmailStatus', type: 'STRING' },
  { name: 'membership_type', prop: 'membershipType', type: 'STRING' },
  { name: 'discount_percent', prop: 'discountPercent', type: 'FLOAT64' },
  { name: 'membership_discount_amount', prop: 'membershipDiscountAmount', type: 'FLOAT64' },
  { name: 'status', prop: 'status', type: 'STRING' },
  { name: 'status_notes', prop: 'statusNotes', type: 'STRING' },
  { name: 'receipt_manual_discount', prop: 'receiptManualDiscount', type: 'FLOAT64' },
  { name: 'receipt_reconciliation', prop: 'receiptReconciliation', type: 'STRING' },
  { name: 'booking_note', prop: 'bookingNote', type: 'STRING' },
];
