export const componentThai: Record<string, string> = {
  'Quick appointment': 'เพิ่มนัดหมายด่วน',
  'Save now. Handle payment and medical history separately.': 'บันทึกนัดหมายก่อน แล้วจัดการการชำระเงินและประวัติสุขภาพแยกต่างหาก',
  'Close quick appointment': 'ปิดหน้าต่างเพิ่มนัดหมายด่วน',
  'Internal booking note (optional)': 'บันทึกภายในเกี่ยวกับการจอง (ไม่บังคับ)',
  'For the clinic team, e.g. client requested Tanya': 'สำหรับทีมคลินิก เช่น ลูกค้าขอรับบริการกับ Tanya',
  'Shared with authorized staff and the assigned therapist. Not included in customer emails or receipts. Do not enter medical information here.': 'เจ้าหน้าที่ที่ได้รับอนุญาตและผู้ให้บริการที่ได้รับมอบหมายอ่านได้ ไม่แสดงในอีเมลหรือใบเสร็จของลูกค้า กรุณาอย่าบันทึกข้อมูลสุขภาพที่นี่',
  'Client name': 'ชื่อลูกค้า',
  'Customer name': 'ชื่อลูกค้า',
  'Email or phone number': 'อีเมลหรือหมายเลขโทรศัพท์',
  'client@example.com or +1 437 898 7424': 'client@example.com หรือ +1 437 898 7424',
  'Therapist': 'ผู้ให้บริการ',
  'Choose therapist': 'เลือกผู้ให้บริการ',
  'Second therapist': 'ผู้ให้บริการคนที่สอง',
  'Choose a different therapist': 'เลือกผู้ให้บริการอีกคน',
  'Time': 'เวลา',
  'Date': 'วันที่',
  'Branch': 'สาขา',
  'Service': 'บริการ',
  'No eligible therapists are scheduled for this branch, date, and service. Choose different appointment details.': 'ไม่มีผู้ให้บริการที่มีคุณสมบัติเหมาะสมเข้าเวรในสาขา วันที่ และบริการที่เลือก กรุณาเปลี่ยนรายละเอียดนัดหมาย',
  'Cancel': 'ยกเลิก',
  'Saving...': 'กำลังบันทึก...',
  'Save appointment': 'บันทึกนัดหมาย',
  'Unable to save this appointment.': 'ไม่สามารถบันทึกนัดหมายนี้ได้',
  'Phone-only booking; no email confirmation sent.': 'จองด้วยหมายเลขโทรศัพท์เท่านั้น จึงไม่ได้ส่งอีเมลยืนยัน',
  'Confirmation email sent.': 'ส่งอีเมลยืนยันแล้ว',
  'Confirmation email was not sent: {error}': 'ไม่ได้ส่งอีเมลยืนยัน: {error}',
  'Appointment {id} saved. No payment collected. {confirmation}': 'บันทึกนัดหมาย {id} แล้ว ยังไม่มีการเรียกเก็บเงิน {confirmation}',
  'Shared internal booking note': 'บันทึกภายในเกี่ยวกับการจองสำหรับทีม',
  "For everyone's reference in the clinic": 'สำหรับให้ทุกคนในคลินิกใช้อ้างอิง',
  'Visible to authorized staff and the assigned therapist, not customers. Keep medical information in patient notes.': 'เฉพาะเจ้าหน้าที่ที่ได้รับอนุญาตและผู้ให้บริการที่ได้รับมอบหมายอ่านได้ ลูกค้าอ่านไม่ได้ กรุณาบันทึกข้อมูลสุขภาพในบันทึกผู้ป่วย',
  'Save booking note': 'บันทึกหมายเหตุการจอง',
  'Internal booking note saved for the clinic team.': 'บันทึกหมายเหตุภายในสำหรับทีมคลินิกแล้ว',
  'Unable to save the booking note.': 'ไม่สามารถบันทึกหมายเหตุการจองได้',
  'Choose start and end dates, with the end date on or after the start date.': 'กรุณาเลือกวันเริ่มต้นและวันสิ้นสุด โดยวันสิ้นสุดต้องไม่อยู่ก่อนวันเริ่มต้น',
  '{start} to {end} (inclusive)': '{start} ถึง {end} (รวมวันสิ้นสุด)',
  'all dates': 'ทุกวันที่',
  'All dates': 'ทุกวันที่',
  'unknown': 'ไม่ทราบ',
  'Unknown': 'ไม่ทราบ',
  'Appending missing Wix bookings for {scope} to the primary Google Calendar...': 'กำลังเพิ่มการจอง Wix ที่ยังไม่มีใน Google Calendar หลัก สำหรับ {scope}...',
  '{synced} Wix bookings appended for {scope}; {pending} remaining in this selection.': 'เพิ่มการจอง Wix แล้ว {synced} รายการ สำหรับ {scope} ยังเหลือ {pending} รายการในช่วงที่เลือก',
  'Wix Calendar sync complete for {scope}: {synced} bookings appended. Existing synced appointments were left unchanged.': 'ซิงค์ปฏิทิน Wix สำหรับ {scope} เสร็จแล้ว เพิ่มการจอง {synced} รายการ โดยไม่ได้เปลี่ยนแปลงนัดหมายที่ซิงค์ไว้แล้ว',
  'Unable to sync Wix bookings. Retry to resume.': 'ไม่สามารถซิงค์การจอง Wix ได้ กรุณาลองอีกครั้งเพื่อดำเนินการต่อ',
  'Append missing imported Wix bookings to this Google Calendar across all branches. Existing synced appointments are unchanged. Cancelled/no-show visits are skipped. Keep this tab open until complete.': 'เพิ่มการจอง Wix ที่นำเข้าแล้วแต่ยังไม่มีใน Google Calendar นี้จากทุกสาขา โดยไม่เปลี่ยนแปลงนัดหมายที่ซิงค์แล้ว ข้ามรายการที่ยกเลิกหรือไม่มาตามนัด กรุณาเปิดแท็บนี้ไว้จนเสร็จ',
  'Sync dates': 'วันที่ที่จะซิงค์',
  'Selected date range': 'ช่วงวันที่ที่เลือก',
  'Start date': 'วันเริ่มต้น',
  'End date (inclusive)': 'วันสิ้นสุด (รวมวันนี้)',
  'Syncing Wix bookings...': 'กำลังซิงค์การจอง Wix...',
  'Sync Wix bookings': 'ซิงค์การจอง Wix',
  'Calendar: {synced} bookings synced in this run; {pending} remaining.': 'ปฏิทิน: ซิงค์แล้ว {synced} รายการในรอบนี้ ยังเหลือ {pending} รายการ',
  'Syncing existing Wix bookings to Calendar...': 'กำลังซิงค์การจอง Wix ที่มีอยู่ไปยังปฏิทิน...',
  'Unable to sync Calendar. Retry to resume.': 'ไม่สามารถซิงค์ปฏิทินได้ กรุณาลองอีกครั้งเพื่อดำเนินการต่อ',
  'Unable to load current catalogue.': 'ไม่สามารถโหลดรายการบริการปัจจุบันได้',
  'Unable to load current therapists.': 'ไม่สามารถโหลดรายชื่อผู้ให้บริการปัจจุบันได้',
  'Choose the Wix bookings CSV export.': 'กรุณาเลือกไฟล์ CSV การจองที่ส่งออกจาก Wix',
  'The CSV must be 3 MiB or smaller. Split larger exports before importing.': 'ไฟล์ CSV ต้องมีขนาดไม่เกิน 3 MiB กรุณาแบ่งไฟล์ที่ใหญ่กว่านี้ก่อนนำเข้า',
  'Unable to preview Wix bookings.': 'ไม่สามารถแสดงตัวอย่างการจอง Wix ได้',
  'Unable to import Wix bookings.': 'ไม่สามารถนำเข้าการจอง Wix ได้',
  '{error} If the request timed out, check Events & bookings and retry the same CSV; existing IDs are skipped.': '{error} หากคำขอหมดเวลา กรุณาตรวจสอบในกิจกรรมและการจอง แล้วลองนำเข้า CSV เดิมอีกครั้ง ระบบจะข้ามรหัสที่มีอยู่แล้ว',
  'Unable to review catalogue prices.': 'ไม่สามารถตรวจสอบราคาจากรายการบริการได้',
  'Import historical Wix bookings': 'นำเข้าประวัติการจองจาก Wix',
  'Destination: the existing BigQuery bookings table, for': 'ปลายทางคือตารางการจองเดิมใน BigQuery สำหรับ',
  '. No tables or schema changes are created. Bookings receive stable Wix-prefixed IDs. Re-imports can fill zero-amount Wix records without receipts; existing recorded payments and receipts are preserved.': ' โดยไม่สร้างตารางหรือเปลี่ยนโครงสร้างข้อมูล การจองจะได้รับรหัสคงที่ที่ขึ้นต้นด้วย Wix การนำเข้าซ้ำสามารถเติมยอดเงินให้รายการ Wix ที่มียอดเป็นศูนย์และยังไม่มีใบเสร็จได้ โดยคงข้อมูลการชำระเงินและใบเสร็จที่บันทึกไว้แล้ว',
  'The CSV has no payment amounts. Map each Wix service to a current catalogue service, review the tax-inclusive prices, and confirm that these amounts may be used for the paid records and receipts. These are owner-approved current prices, not historical amounts verified by Wix. Original Wix details remain in notes. Each CSV row represents one booking; prices are not multiplied by spots filled. Four-session package visits use one-quarter of the package subtotal; register and link a verified package in Package tracking to deduct sessions.': 'CSV ไม่มีข้อมูลยอดชำระเงิน กรุณาจับคู่บริการ Wix แต่ละรายการกับบริการปัจจุบัน ตรวจสอบราคารวมภาษี และยืนยันว่าใช้ยอดเหล่านี้ในบันทึกการชำระเงินและใบเสร็จได้ ราคาเหล่านี้เป็นราคาปัจจุบันที่เจ้าของอนุมัติ ไม่ใช่ยอดย้อนหลังที่ Wix ตรวจสอบแล้ว รายละเอียดเดิมจาก Wix จะคงอยู่ในหมายเหตุ CSV แต่ละแถวแทนการจองหนึ่งรายการ โดยไม่คูณราคาตามจำนวนที่นั่งที่จอง การใช้แพ็กเกจ 4 ครั้งจะคิดหนึ่งในสี่ของราคาแพ็กเกจก่อนภาษี กรุณาลงทะเบียนและเชื่อมโยงแพ็กเกจที่ตรวจสอบแล้วในหน้าติดตามแพ็กเกจเพื่อหักจำนวนครั้ง',
  'Session times are interpreted in the clinic timezone. Future session dates are skipped. Staff names and original Wix fields are preserved; mapped service labels are used for receipts. Imports automatically sync to the primary Google Calendar in batches. Cancelled/no-show bookings are not added. No invitation emails, reminders, receipts, charges, or loyalty points are generated. Keep this page open until syncing finishes; retry/backfill resumes unsynced bookings without duplicates.': 'ระบบอ่านเวลานัดหมายตามเขตเวลาของคลินิก และข้ามนัดหมายในอนาคต ชื่อเจ้าหน้าที่และข้อมูลเดิมจาก Wix จะคงไว้ โดยใช้ชื่อบริการที่จับคู่ในใบเสร็จ การนำเข้าจะซิงค์ไปยัง Google Calendar หลักเป็นชุดโดยอัตโนมัติ ไม่เพิ่มรายการที่ยกเลิกหรือไม่มาตามนัด ไม่ส่งอีเมลเชิญหรือเตือน ไม่ออกใบเสร็จ เรียกเก็บเงิน หรือเพิ่มคะแนนสะสม กรุณาเปิดหน้านี้ไว้จนซิงค์เสร็จ การลองใหม่หรือซิงค์ย้อนหลังจะดำเนินการต่อเฉพาะรายการที่ยังไม่ซิงค์โดยไม่สร้างรายการซ้ำ',
  'Sync existing Wix bookings to Calendar': 'ซิงค์การจอง Wix ที่มีอยู่ไปยังปฏิทิน',
  'Preview Wix bookings CSV (up to 3 MiB / 10,000 records)': 'ดูตัวอย่าง CSV การจอง Wix (ไม่เกิน 3 MiB / 10,000 รายการ)',
  'Processing historical bookings...': 'กำลังประมวลผลประวัติการจอง...',
  '{error} Reload this page to retry loading the catalogue.': '{error} กรุณาโหลดหน้านี้ใหม่เพื่อลองโหลดรายการบริการอีกครั้ง',
  '{filename}: {rows} rows, {valid} unique valid bookings, {duplicates} duplicates, {invalid} invalid rows and {future} future sessions skipped.': '{filename}: {rows} แถว มีการจองที่ถูกต้องและไม่ซ้ำ {valid} รายการ ข้ามรายการซ้ำ {duplicates} รายการ แถวที่ไม่ถูกต้อง {invalid} แถว และนัดหมายในอนาคต {future} รายการ',
  'Through {date}.': 'ถึงวันที่ {date}',
  'Import range: {start} to {end}.': 'ช่วงวันที่นำเข้า: {start} ถึง {end}',
  '{count} bookings have missing names or invalid contact/registration values; originals retained in notes.': 'การจอง {count} รายการไม่มีชื่อหรือมีข้อมูลติดต่อ/ลงทะเบียนไม่ถูกต้อง โดยเก็บข้อมูลเดิมไว้ในหมายเหตุ',
  'CSV record {row}: {message}': 'รายการ CSV ที่ {row}: {message}',
  'First five valid bookings in chronological order': 'การจองที่ถูกต้อง 5 รายการแรก เรียงตามเวลา',
  'Booking / client': 'การจอง / ลูกค้า',
  'Session': 'นัดหมาย',
  'Staff': 'เจ้าหน้าที่',
  'Duration': 'ระยะเวลา',
  'Status': 'สถานะ',
  'Total / paid': 'ยอดรวม / ชำระแล้ว',
  '{minutes} min': '{minutes} นาที',
  'Map Wix therapist names': 'จับคู่ชื่อผู้ให้บริการจาก Wix',
  'Choose the current therapist for each Wix staff name, or keep the original name for former/unknown staff. Original Wix names and booking IDs are preserved. Mapping applies to newly imported bookings; re-import does not reassign existing bookings.': 'เลือกผู้ให้บริการปัจจุบันสำหรับแต่ละชื่อเจ้าหน้าที่ใน Wix หรือคงชื่อเดิมสำหรับเจ้าหน้าที่เก่าหรือไม่ทราบชื่อ ระบบจะคงชื่อเดิมและรหัสการจองจาก Wix การจับคู่ใช้กับการจองที่นำเข้าใหม่เท่านั้น การนำเข้าซ้ำจะไม่เปลี่ยนผู้ให้บริการของการจองที่มีอยู่',
  '{error} Reload to retry; you can still keep the original Wix names.': '{error} กรุณาโหลดหน้าใหม่เพื่อลองอีกครั้ง คุณยังสามารถคงชื่อเดิมจาก Wix ได้',
  'No Wix staff name': 'ไม่มีชื่อเจ้าหน้าที่ใน Wix',
  '{count} bookings': 'การจอง {count} รายการ',
  'Keep original Wix name': 'คงชื่อเดิมจาก Wix',
  ' (blank)': ' (ว่าง)',
  'Review current catalogue prices': 'ตรวจสอบราคาบริการปัจจุบัน',
  'Select a catalogue service': 'เลือกบริการจากรายการ',
  ' per session (4-session package)': ' ต่อครั้ง (แพ็กเกจ 4 ครั้ง)',
  '{rate}% tax': 'ภาษี {rate}%',
  'Preview mapped prices & therapists': 'ดูตัวอย่างราคาและผู้ให้บริการที่จับคู่',
  'Tax-inclusive total for this CSV: ${total}. Each mapped booking will be marked paid in full.': 'ยอดรวมภาษีสำหรับ CSV นี้: ${total} การจองที่จับคู่แต่ละรายการจะถูกระบุว่าชำระเต็มจำนวนแล้ว',
  '{count} bookings mapped to current therapists; other staff names kept as exported.': 'จับคู่การจอง {count} รายการกับผู้ให้บริการปัจจุบันแล้ว ชื่อเจ้าหน้าที่อื่นคงไว้ตามข้อมูลที่ส่งออก',
  'I confirm these historical bookings were paid and approve the reviewed current catalogue prices for their records and receipts. These prices may differ from the original charges.': 'ฉันยืนยันว่าการจองย้อนหลังเหล่านี้ชำระเงินแล้ว และอนุมัติให้ใช้ราคาบริการปัจจุบันที่ตรวจสอบแล้วในบันทึกและใบเสร็จ ราคาเหล่านี้อาจต่างจากยอดที่เรียกเก็บเดิม',
  'Import {count} paid bookings': 'นำเข้าการจองที่ชำระแล้ว {count} รายการ',
  'Imported {imported} new paid bookings; updated {updated} zero-amount Wix records; skipped {existing} existing paid/receipt records. Issue receipts individually in Events & bookings (valid email required).': 'นำเข้าการจองที่ชำระแล้วใหม่ {imported} รายการ ปรับปรุงรายการ Wix ที่มียอดเป็นศูนย์ {updated} รายการ และข้ามรายการที่มีการชำระเงิน/ใบเสร็จอยู่แล้ว {existing} รายการ ออกใบเสร็จทีละรายการในกิจกรรมและการจอง (ต้องมีอีเมลที่ถูกต้อง)',
  'View Events & bookings': 'ดูกิจกรรมและการจอง',
  'Unable to process Wix contacts.': 'ไม่สามารถประมวลผลข้อมูลติดต่อจาก Wix ได้',
  'Choose the Wix contacts CSV export.': 'กรุณาเลือกไฟล์ CSV ข้อมูลติดต่อที่ส่งออกจาก Wix',
  '{error} If the request timed out, refresh the list; re-importing the same CSV safely skips existing contacts.': '{error} หากคำขอหมดเวลา กรุณารีเฟรชรายการ การนำเข้า CSV เดิมซ้ำจะข้ามข้อมูลติดต่อที่มีอยู่แล้วอย่างปลอดภัย',
  'Historical Wix contacts': 'ข้อมูลติดต่อย้อนหลังจาก Wix',
  'Import a Wix contacts CSV into a separate BigQuery contact archive. Existing bookings, patient records, payments and loyalty data are not changed.': 'นำเข้า CSV ข้อมูลติดต่อจาก Wix ไปยังคลังข้อมูลติดต่อแยกใน BigQuery โดยไม่เปลี่ยนแปลงการจอง เวชระเบียน การชำระเงิน หรือข้อมูลคะแนนสะสมที่มีอยู่',
  'Subscription statuses are historical only. This import does not send emails, enroll members or grant marketing consent. Duplicate primary emails (or phone numbers when email is missing) are skipped; existing imported contacts are never overwritten.': 'สถานะการสมัครรับข่าวสารเป็นข้อมูลย้อนหลังเท่านั้น การนำเข้านี้ไม่ส่งอีเมล สมัครสมาชิก หรือให้ความยินยอมทางการตลาด ระบบจะข้ามอีเมลหลักที่ซ้ำ (หรือหมายเลขโทรศัพท์เมื่อไม่มีอีเมล) และไม่เขียนทับข้อมูลติดต่อที่นำเข้าไว้แล้ว',
  'Preview Wix CSV (up to 3 MiB / 10,000 contacts)': 'ดูตัวอย่าง CSV จาก Wix (ไม่เกิน 3 MiB / 10,000 รายชื่อ)',
  'Processing contacts...': 'กำลังประมวลผลข้อมูลติดต่อ...',
  '{filename}: {rows} rows, {valid} unique valid contacts, {invalid} invalid rows skipped, {duplicates} CSV duplicates skipped.': '{filename}: {rows} แถว มีข้อมูลติดต่อที่ถูกต้องและไม่ซ้ำ {valid} รายชื่อ ข้ามแถวที่ไม่ถูกต้อง {invalid} แถว และรายการซ้ำใน CSV {duplicates} รายการ',
  '{count} contacts have unrecognized dates; original values are retained.': 'ข้อมูลติดต่อ {count} รายชื่อมีวันที่ที่ระบบอ่านไม่ได้ โดยคงค่าเดิมไว้',
  'Imported {imported} new contacts. Skipped {existing} contacts already in the archive.': 'นำเข้าข้อมูลติดต่อใหม่ {imported} รายชื่อ และข้ามข้อมูลที่มีในคลังแล้ว {existing} รายชื่อ',
  'Preview: first five valid contacts': 'ตัวอย่าง: ข้อมูลติดต่อที่ถูกต้อง 5 รายชื่อแรก',
  'Name': 'ชื่อ',
  'Email': 'อีเมล',
  'Phone': 'โทรศัพท์',
  'Email status': 'สถานะอีเมล',
  'Not provided': 'ไม่ได้ระบุ',
  'Import {count} contacts': 'นำเข้าข้อมูลติดต่อ {count} รายชื่อ',
  'Search imported contacts': 'ค้นหาข้อมูลติดต่อที่นำเข้า',
  'Search name, email, phone or labels': 'ค้นหาชื่อ อีเมล โทรศัพท์ หรือป้ายกำกับ',
  'Search': 'ค้นหา',
  'Refresh imported contacts': 'รีเฟรชข้อมูลติดต่อที่นำเข้า',
  'Loading imported contacts...': 'กำลังโหลดข้อมูลติดต่อที่นำเข้า...',
  '{count} matching contacts': 'พบข้อมูลติดต่อ {count} รายชื่อ',
  'Contact': 'ข้อมูลติดต่อ',
  'Labels': 'ป้ายกำกับ',
  'Wix created (UTC)': 'วันที่สร้างใน Wix (UTC)',
  'Email / SMS status': 'สถานะอีเมล / SMS',
  'Last activity (UTC)': 'กิจกรรมล่าสุด (UTC)',
  'Source / locations': 'แหล่งที่มา / สถานที่',
  'No imported contacts found.': 'ไม่พบข้อมูลติดต่อที่นำเข้า',
  'Previous': 'ก่อนหน้า',
  'Next': 'ถัดไป',
  '{start}-{end} of {total}': '{start}-{end} จาก {total}',
  '0 contacts': '0 รายชื่อ',
  'Unable to update packages.': 'ไม่สามารถปรับปรุงข้อมูลแพ็กเกจได้',
  'Package {id} registered/verified. Remaining: {remaining} of 4.': 'ลงทะเบียน/ตรวจสอบแพ็กเกจ {id} แล้ว เหลือ {remaining} จาก 4 ครั้ง',
  'Already linked; no duplicate deduction.': 'เชื่อมโยงไว้แล้ว ไม่มีการหักซ้ำ',
  'Deducted one session.': 'หักแล้ว 1 ครั้ง',
  '{result} {remaining} sessions remained after this visit. Receipt is now available in Events & bookings.': '{result} หลังการรับบริการครั้งนี้เหลือ {remaining} ครั้ง สามารถออกใบเสร็จได้แล้วในกิจกรรมและการจอง',
  '{error} Refresh and retry if another update occurred; the same booking is never deducted twice.': '{error} หากมีการปรับปรุงข้อมูลจากที่อื่น กรุณารีเฟรชและลองอีกครั้ง ระบบจะไม่หักการจองเดียวกันซ้ำ',
  'Four-session package tracking': 'ติดตามแพ็กเกจ 4 ครั้ง',
  'Register an owner-verified purchase and remaining balance. Then link each completed visit once to deduct a session. Wix exports do not establish package purchases. Register a new purchase with a different reference; reusing a reference never replenishes a balance.': 'ลงทะเบียนการซื้อและจำนวนครั้งคงเหลือที่เจ้าของตรวจสอบแล้ว จากนั้นเชื่อมโยงการรับบริการที่เสร็จสิ้นแต่ละครั้งเพียงครั้งเดียวเพื่อหักจำนวนครั้ง ข้อมูลที่ส่งออกจาก Wix ไม่ใช่หลักฐานการซื้อแพ็กเกจ การซื้อใหม่ต้องใช้เลขอ้างอิงใหม่ การใช้เลขอ้างอิงเดิมซ้ำจะไม่เพิ่มจำนวนครั้งคงเหลือ',
  'If entering a remaining balance that already accounts for old visits, do not deduct those visits again. To link old visits for receipt tracking, register the verified balance before those visits and link them chronologically. Use the actual package purchase price. A linked receipt records an allocated prepaid session value, not a new charge.': 'หากจำนวนครั้งคงเหลือที่กรอกรวมการหักการรับบริการที่ผ่านมาแล้ว อย่าหักรายการเหล่านั้นอีก หากต้องการเชื่อมโยงรายการเก่าเพื่อติดตามใบเสร็จ ให้ลงทะเบียนยอดที่ตรวจสอบแล้วก่อนรายการเหล่านั้น และเชื่อมโยงตามลำดับเวลา ใช้ราคาที่ซื้อแพ็กเกจจริง ใบเสร็จที่เชื่อมโยงจะบันทึกมูลค่าที่จัดสรรจากเงินจ่ายล่วงหน้าต่อครั้ง ไม่ใช่การเรียกเก็บเงินใหม่',
  'Register / verify a package': 'ลงทะเบียน / ตรวจสอบแพ็กเกจ',
  'Customer email': 'อีเมลลูกค้า',
  'Package name': 'ชื่อแพ็กเกจ',
  'Unique purchase reference': 'เลขอ้างอิงการซื้อที่ไม่ซ้ำ',
  'Purchase date': 'วันที่ซื้อ',
  'Minutes per session': 'จำนวนนาทีต่อครั้ง',
  'Verified sessions remaining (0-4)': 'จำนวนครั้งคงเหลือที่ตรวจสอบแล้ว (0-4)',
  'Full four-session package price before tax ($)': 'ราคาแพ็กเกจ 4 ครั้งเต็มก่อนภาษี ($)',
  'Tax rate': 'อัตราภาษี',
  '13% HST - regular massage': 'HST 13% - การนวดทั่วไป',
  '0% - RMT/acupuncture': '0% - นวดโดย RMT/ฝังเข็ม',
  'I have verified the prepaid purchase, full package price, and starting balance. This registration does not charge or email the customer.': 'ฉันตรวจสอบการซื้อแบบจ่ายล่วงหน้า ราคาแพ็กเกจเต็ม และจำนวนครั้งเริ่มต้นแล้ว การลงทะเบียนนี้ไม่เรียกเก็บเงินหรือส่งอีเมลถึงลูกค้า',
  'Register verified package': 'ลงทะเบียนแพ็กเกจที่ตรวจสอบแล้ว',
  'Search packages by customer, email or purchase reference': 'ค้นหาแพ็กเกจตามลูกค้า อีเมล หรือเลขอ้างอิงการซื้อ',
  'Find customer / email / purchase reference': 'ค้นหาลูกค้า / อีเมล / เลขอ้างอิงการซื้อ',
  'Search / refresh': 'ค้นหา / รีเฟรช',
  'Loading packages...': 'กำลังโหลดแพ็กเกจ...',
  'Customer': 'ลูกค้า',
  'Package / purchase': 'แพ็กเกจ / การซื้อ',
  'Balance': 'คงเหลือ',
  'Tracked visits': 'การรับบริการที่ติดตาม',
  'Action': 'การดำเนินการ',
  '{remaining} / 4 remaining': 'เหลือ {remaining} / 4 ครั้ง',
  'Starting verified balance: {balance}': 'จำนวนครั้งเริ่มต้นที่ตรวจสอบแล้ว: {balance}',
  '{count} linked visits': 'เชื่อมโยงการรับบริการแล้ว {count} ครั้ง',
  'View / deduct': 'ดู / หักจำนวนครั้ง',
  'No matching packages.': 'ไม่พบแพ็กเกจที่ตรงกับการค้นหา',
  '{count} packages': '{count} แพ็กเกจ',
  '{package} - {remaining} sessions remaining': '{package} - เหลือ {remaining} ครั้ง',
  '{id} | 1 deducted | {remaining} remained after visit | allocated ${total}': '{id} | หัก 1 ครั้ง | เหลือ {remaining} ครั้งหลังรับบริการ | มูลค่าที่จัดสรร ${total}',
  'Link a completed booking': 'เชื่อมโยงการจองที่รับบริการแล้ว',
  'Select a matching customer/duration booking': 'เลือกการจองที่ตรงกับลูกค้าและระยะเวลาบริการ',
  'The session will be covered by this prepaid package. Its allocated total/paid amount replaces the booking amount before receipt issuance. No new payment is collected. Existing normal paid bookings are rejected; reconstructed Wix payments can be linked.': 'การรับบริการครั้งนี้จะใช้แพ็กเกจที่ชำระล่วงหน้า มูลค่ารวม/ยอดชำระที่จัดสรรจะใช้แทนยอดการจองก่อนออกใบเสร็จ ไม่มีการเรียกเก็บเงินใหม่ ไม่สามารถเชื่อมโยงการจองทั่วไปที่ชำระแล้วได้ แต่เชื่อมโยงรายการ Wix ที่สร้างยอดชำระขึ้นใหม่ได้',
  'I confirm this visit occurred, belongs to this package, and has not already been deducted from the registered starting balance.': 'ฉันยืนยันว่ามีการรับบริการครั้งนี้จริง เป็นการใช้แพ็กเกจนี้ และยังไม่ได้หักจากจำนวนครั้งเริ่มต้นที่ลงทะเบียนไว้',
  'Deduct one session & link receipt': 'หัก 1 ครั้งและเชื่อมโยงใบเสร็จ',
  'View bookings / issue receipt': 'ดูการจอง / ออกใบเสร็จ',
  'Server returned status {status}': 'เซิร์ฟเวอร์ตอบกลับด้วยสถานะ {status}',
  'Unable to preview past bookings.': 'ไม่สามารถแสดงตัวอย่างการจองที่ผ่านมาได้',
  'Cleared {count} past bookings. Package and loyalty ledgers were not changed.': 'ลบการจองที่ผ่านมา {count} รายการแล้ว โดยไม่เปลี่ยนแปลงบัญชีแพ็กเกจและคะแนนสะสม',
  'Unable to clear past bookings.': 'ไม่สามารถลบการจองที่ผ่านมาได้',
  'Clear past booking history': 'ลบประวัติการจองที่ผ่านมา',
  'All branches, including Wix imports. Future and ongoing appointments are kept.': 'ครอบคลุมทุกสาขา รวมรายการที่นำเข้าจาก Wix โดยเก็บนัดหมายในอนาคตและที่กำลังดำเนินอยู่ไว้',
  'Working...': 'กำลังดำเนินการ...',
  'Clear past bookings': 'ลบการจองที่ผ่านมา',
  'will be permanently deleted, including {paid} paid bookings and {receipts} issued receipt records.': 'จะถูกลบอย่างถาวร รวมการจองที่ชำระแล้ว {paid} รายการ และบันทึกใบเสร็จที่ออกแล้ว {receipts} รายการ',
  '{kept} bookings will be kept. Cutoff: {cutoff} ({zone}).': 'จะเก็บการจอง {kept} รายการไว้ เวลาตัดยอด: {cutoff} ({zone})',
  'No archive is created. Stored booking payment and receipt details will be lost and cannot be reissued from the dashboard. Package balances and usage, loyalty ledgers, separate Square payment records, contacts, patient records, and Google Calendar events are not deleted. Past bookings with invalid dates, times, or durations are kept for manual review. Booking-based reports will no longer include deleted visits. Reimporting the Wix CSV can recreate deleted bookings.': 'ไม่มีการสร้างคลังสำรอง รายละเอียดการชำระเงินและใบเสร็จของการจองจะสูญหาย และไม่สามารถออกใบเสร็จซ้ำจากแดชบอร์ดได้ จำนวนครั้งคงเหลือและการใช้แพ็กเกจ บัญชีคะแนนสะสม บันทึกการชำระเงินแยกใน Square ข้อมูลติดต่อ เวชระเบียน และกิจกรรมใน Google Calendar จะไม่ถูกลบ การจองที่ผ่านมาซึ่งมีวันที่ เวลา หรือระยะเวลาไม่ถูกต้องจะคงไว้เพื่อตรวจสอบด้วยตนเอง รายงานที่อ้างอิงการจองจะไม่รวมรายการที่ลบแล้ว การนำเข้า CSV จาก Wix ซ้ำอาจสร้างการจองที่ลบไปแล้วขึ้นใหม่',
  'Type {confirmation} to confirm': 'พิมพ์ {confirmation} เพื่อยืนยัน',
  'Permanently delete {count} past bookings': 'ลบการจองที่ผ่านมา {count} รายการอย่างถาวร',
  'Confirmed': 'ยืนยันแล้ว',
  'Completed': 'เสร็จสิ้น',
  'Cancelled': 'ยกเลิกแล้ว',
  'No-show': 'ไม่มาตามนัด',
  'No Show': 'ไม่มาตามนัด',
  'Subscribed': 'สมัครรับข่าวสารแล้ว',
  'Unsubscribed': 'ยกเลิกรับข่าวสารแล้ว',
  'Not subscribed': 'ไม่ได้สมัครรับข่าวสาร',
  'Never subscribed': 'ไม่เคยสมัครรับข่าวสาร',
  'Pending': 'รอดำเนินการ',
  'Thai Massage': 'นวดไทย',
  'Thai Traditional Massage (30 min)': 'นวดไทยแผนโบราณ (30 นาที)',
  'Thai Traditional Massage (60 min)': 'นวดไทยแผนโบราณ (60 นาที)',
  'Thai Traditional Massage (90 min)': 'นวดไทยแผนโบราณ (90 นาที)',
  'Thai Traditional Massage (120 min)': 'นวดไทยแผนโบราณ (120 นาที)',
  'Thai Traditional Massage - Couple (60 min)': 'นวดไทยแผนโบราณสำหรับคู่ (60 นาที)',
  'Thai Traditional Massage - Couple (90 min)': 'นวดไทยแผนโบราณสำหรับคู่ (90 นาที)',
  'Thai Combination Swedish (30 min)': 'นวดไทยผสมสวีดิช (30 นาที)',
  'Thai Combination Swedish (60 min)': 'นวดไทยผสมสวีดิช (60 นาที)',
  'Thai Combination Swedish (90 min)': 'นวดไทยผสมสวีดิช (90 นาที)',
  'Thai Combination Swedish - Couple (60 min)': 'นวดไทยผสมสวีดิชสำหรับคู่ (60 นาที)',
  'Thai Combination Swedish - Couple (90 min)': 'นวดไทยผสมสวีดิชสำหรับคู่ (90 นาที)',
  'Thai Combo Swedish + Hot Stone (60 min)': 'นวดไทยผสมสวีดิชและหินร้อน (60 นาที)',
  'Thai Combo Swedish + Hot Stone (90 min)': 'นวดไทยผสมสวีดิชและหินร้อน (90 นาที)',
  'Thai Combo Swedish + Hot Stone - Couple (60 min)': 'นวดไทยผสมสวีดิชและหินร้อนสำหรับคู่ (60 นาที)',
  'Thai Combo Swedish + Hot Stone - Couple (90 min)': 'นวดไทยผสมสวีดิชและหินร้อนสำหรับคู่ (90 นาที)',
  'Hot Stone Add-On': 'บริการเสริมหินร้อน',
  'Registered Massage Therapy (RMT 60 min)': 'นวดบำบัดโดยนักนวดบำบัดที่ขึ้นทะเบียน (RMT 60 นาที)',
  'Registered Massage Therapy (RMT 90 min)': 'นวดบำบัดโดยนักนวดบำบัดที่ขึ้นทะเบียน (RMT 90 นาที)',
  'Traditional Thai Acupuncture (60 min)': 'ฝังเข็มแผนไทย (60 นาที)',
  'RMT Massage': 'นวดโดยนักนวดบำบัดที่ขึ้นทะเบียน (RMT)',
  'Couple Massage': 'นวดสำหรับคู่',
  'Package: 60 min x 4 Sessions': 'แพ็กเกจ: 60 นาที x 4 ครั้ง',
  'Package: 90 min x 4 Sessions': 'แพ็กเกจ: 90 นาที x 4 ครั้ง',
};
