export const dashboardThai: Record<string, string> = {
  'Use Edit booking to update a booking with a saved manual discount.': 'กรุณาใช้หน้าแก้ไขการจองเพื่ออัปเดตการจองที่มีส่วนลดบันทึกไว้',
  'Apply manual discounts in Edit booking, not Issue receipt.': 'กรุณาใช้ส่วนลดที่กำหนดเองในหน้าแก้ไขการจอง ไม่ใช่หน้าออกใบเสร็จ',
  'Total after discount: $': 'ยอดรวมหลังหักส่วนลด: $',
  'Discounts are deducted before HST. Saved totals sync to bookings, calendar and receipts. No payment or refund is sent automatically.': 'หักส่วนลดก่อนภาษี HST ยอดที่บันทึกจะซิงค์กับการจอง ปฏิทิน และใบเสร็จ โดยไม่เรียกเก็บเงินหรือคืนเงินโดยอัตโนมัติ',
  'I confirm any external payment adjustment or refund has been handled. Save the discounted total and reconciled payment record.': 'ฉันยืนยันว่าดำเนินการปรับยอดชำระหรือคืนเงินภายนอกแล้ว ให้บันทึกยอดหลังส่วนลดและข้อมูลชำระเงินที่กระทบยอดแล้ว',
  'Confirm reconciliation before saving the booking discount.': 'กรุณายืนยันการกระทบยอดก่อนบันทึกส่วนลดการจอง',
  'The manual discount cannot exceed the appointment subtotal.': 'ส่วนลดที่กำหนดเองต้องไม่เกินยอดก่อนภาษีของนัดหมาย',
  'This booking has protected payment details. Its manual discount cannot be changed.': 'การจองนี้มีข้อมูลชำระเงินที่ได้รับการป้องกัน ไม่สามารถเปลี่ยนส่วนลดได้',
  'Resolve linked loyalty redemptions before applying a manual booking discount.': 'กรุณาจัดการรายการใช้แต้มที่เชื่อมโยงก่อนใช้ส่วนลดการจองที่กำหนดเอง',
  'The saved booking discount does not match the payment record. Reconcile the booking before editing or issuing a receipt.': 'ส่วนลดการจองที่บันทึกไว้ไม่ตรงกับข้อมูลชำระเงิน กรุณากระทบยอดก่อนแก้ไขหรือออกใบเสร็จ',
  'Manual discounts are no longer available.': 'ไม่สามารถใช้ส่วนลดที่กำหนดเองได้อีกต่อไป',
  'Stored receipt reconciliation has no issued receipt. Correct the booking record before issuing a receipt.': 'ข้อมูลกระทบยอดที่บันทึกไว้ไม่มีใบเสร็จที่ออกแล้ว กรุณาแก้ไขข้อมูลการจองก่อนออกใบเสร็จ',
  'Review the total and amount paid when changing a service.': 'ตรวจสอบยอดรวมและยอดชำระเมื่อเปลี่ยนบริการ',
  'Booking saved.': 'บันทึกการจองแล้ว',
  'Booking saved, but refreshed data could not be loaded. Refresh before making further changes.': 'บันทึกการจองแล้ว แต่ไม่สามารถโหลดข้อมูลล่าสุดได้ กรุณารีเฟรชก่อนแก้ไขเพิ่มเติม',
  'Edit booking': 'แก้ไขการจอง',
  'Close booking editor': 'ปิดหน้าต่างแก้ไขการจอง',
  'Save booking': 'บันทึกการจอง',
  'Unable to save this booking.': 'ไม่สามารถบันทึกการจองนี้ได้',
  'Changes update the database and linked calendar appointment. No payment or refund is sent automatically.': 'การเปลี่ยนแปลงจะอัปเดตฐานข้อมูลและนัดหมายในปฏิทินที่เชื่อมโยง โดยจะไม่เรียกเก็บเงินหรือคืนเงินโดยอัตโนมัติ',
  'Review the total and amount paid when changing a service. Use receipt reconciliation for manual discounts.': 'ตรวจสอบยอดรวมและยอดชำระเมื่อเปลี่ยนบริการ ใช้การยืนยันกระทบยอดใบเสร็จสำหรับส่วนลดที่กำหนดเอง',
  'Issued receipts, prepaid packages and membership records lock customer, service, schedule and payment details. You can still edit the shared note and therapist.': 'ใบเสร็จที่ออกแล้ว แพ็กเกจชำระล่วงหน้า และสมาชิกจะล็อกข้อมูลลูกค้า บริการ เวลานัด และการชำระเงิน แต่ยังแก้ไขหมายเหตุร่วมและผู้ให้บริการได้',
  'This booking changed. Refresh the booking before editing.': 'การจองนี้มีการเปลี่ยนแปลง กรุณารีเฟรชก่อนแก้ไข',
  'Match this booking to a configured branch before editing.': 'กรุณาจับคู่การจองกับสาขาที่ตั้งค่าไว้ก่อนแก้ไข',
  'Choose an active service with a valid duration.': 'กรุณาเลือกบริการที่เปิดใช้งานและมีระยะเวลาถูกต้อง',
  'Choose a scheduled, qualified therapist (two different therapists for a couple session).': 'กรุณาเลือกผู้ให้บริการที่มีคุณสมบัติและอยู่ในตารางงาน (สองคนที่ต่างกันสำหรับบริการคู่)',
  'Completed, cancelled or no-show bookings cannot be rescheduled.': 'ไม่สามารถเปลี่ยนเวลาของการจองที่เสร็จสิ้น ยกเลิก หรือไม่มาตามนัดได้',
  'This time is unavailable. Choose another date, time or therapist.': 'เวลานี้ไม่ว่าง กรุณาเลือกวัน เวลา หรือผู้ให้บริการอื่น',
  'The selected therapist already has an appointment at this time.': 'ผู้ให้บริการที่เลือกมีนัดหมายในเวลานี้แล้ว',
  'The booking could not be saved. Refresh the booking before retrying.': 'ไม่สามารถบันทึกการจองได้ กรุณารีเฟรชก่อนลองอีกครั้ง',
  'The calendar appointment changed. Refresh before editing.': 'นัดหมายในปฏิทินมีการเปลี่ยนแปลง กรุณารีเฟรชก่อนแก้ไข',
  'The calendar update could not be verified. No database edit was attempted. Check and reconcile the calendar before retrying.': 'ไม่สามารถยืนยันการอัปเดตปฏิทินได้ ยังไม่ได้แก้ไขฐานข้อมูล กรุณาตรวจสอบและกระทบยอดปฏิทินก่อนลองอีกครั้ง',
  'The booking update could not be verified. Staff must reconcile the database and calendar before retrying.': 'ไม่สามารถยืนยันการอัปเดตการจองได้ พนักงานต้องตรวจสอบฐานข้อมูลและปฏิทินให้ตรงกันก่อนลองอีกครั้ง',
  'The booking changed during saving. Staff must reconcile the database and calendar before retrying.': 'การจองมีการเปลี่ยนแปลงระหว่างบันทึก พนักงานต้องตรวจสอบฐานข้อมูลและปฏิทินให้ตรงกันก่อนลองอีกครั้ง',
  'The database update failed and Calendar could not be restored. Staff must reconcile this appointment before retrying.': 'อัปเดตฐานข้อมูลไม่สำเร็จและไม่สามารถคืนค่าปฏิทินได้ พนักงานต้องตรวจสอบนัดหมายให้ตรงกันก่อนลองอีกครั้ง',
  'Enter valid booking details.': 'กรุณาระบุข้อมูลการจองที่ถูกต้อง',
  'Enter non-negative payment amounts with at most two decimal places.': 'กรุณาระบุยอดเงินที่ไม่ติดลบและมีทศนิยมไม่เกินสองตำแหน่ง',
  'Choose a payment method.': 'กรุณาเลือกวิธีชำระเงิน',
  'Choose a valid appointment date and time.': 'กรุณาเลือกวันและเวลานัดหมายที่ถูกต้อง',
  'Branches saved. The booking portal will reflect these changes immediately.': 'บันทึกสาขาแล้ว หน้าจองจะแสดงการเปลี่ยนแปลงทันที',
  'Services saved. The booking portal will reflect these changes immediately.': 'บันทึกบริการแล้ว หน้าจองจะแสดงการเปลี่ยนแปลงทันที',
  'Rewards program settings saved.': 'บันทึกการตั้งค่าโปรแกรมสะสมแต้มแล้ว',
  'Unable to create a company portal link.': 'ไม่สามารถสร้างลิงก์สำหรับบริษัทได้',
  'Business profile saved and synced for your owner account.': 'บันทึกและซิงค์ข้อมูลธุรกิจสำหรับบัญชีเจ้าของแล้ว',
  'Therapist roster and branch rotation saved. This syncs to the booking portal and therapist portal immediately.': 'บันทึกรายชื่อผู้ให้บริการและตารางหมุนเวียนสาขาแล้ว ข้อมูลจะซิงค์ไปยังหน้าจองและหน้าผู้ให้บริการทันที',
  'Mon': 'จ.',
  'Tue': 'อ.',
  'Wed': 'พ.',
  'Thu': 'พฤ.',
  'Fri': 'ศ.',
  'Sat': 'ส.',
  'Sun': 'อา.',
  'Booking details saved.': 'บันทึกรายละเอียดการจองแล้ว',
  'Add a subject and message before saving the campaign draft.': 'กรุณาใส่หัวเรื่องและข้อความก่อนบันทึกฉบับร่าง',
  'Campaign saved as a draft on this device. It has not been sent.': 'บันทึกแคมเปญเป็นฉบับร่างบนอุปกรณ์นี้แล้ว ยังไม่ได้ส่ง',
  'Could not save the draft in this browser. Check available browser storage and try again.': 'ไม่สามารถบันทึกฉบับร่างในเบราว์เซอร์นี้ได้ กรุณาตรวจสอบพื้นที่จัดเก็บและลองอีกครั้ง',
  'Could not update saved drafts in this browser.': 'ไม่สามารถอัปเดตฉบับร่างที่บันทึกในเบราว์เซอร์นี้ได้',
  'Describe what this campaign should communicate before generating a draft.': 'กรุณาระบุสิ่งที่ต้องการสื่อสารในแคมเปญก่อนสร้างฉบับร่าง',
  'Add a subject and message before sending.': 'กรุณาใส่หัวเรื่องและข้อความก่อนส่ง',
  'Some campaign emails failed to send. Do not resend until you have checked which messages were delivered.': 'อีเมลบางฉบับส่งไม่สำเร็จ กรุณาตรวจสอบว่าอีเมลใดส่งแล้วก่อนส่งซ้ำ',
  'Allow pop-ups to print the receipt.': 'กรุณาอนุญาตหน้าต่างป๊อปอัปเพื่อพิมพ์ใบเสร็จ',
  'Home': 'หน้าหลัก',
  'Booking Calendar': 'ปฏิทินการจอง',
  'Events & bookings': 'กิจกรรมและการจอง',
  'Sales & reports': 'ยอดขายและรายงาน',
  'Service catalogue': 'รายการบริการ',
  'Staff': 'พนักงาน',
  'Branches': 'สาขา',
  'Availability': 'เวลาว่าง',
  'Patients': 'ลูกค้า',
  'Wix contacts import': 'นำเข้ารายชื่อติดต่อจาก Wix',
  'Wix bookings import': 'นำเข้าการจองจาก Wix',
  'Package tracking': 'ติดตามแพ็กเกจ',
  'Therapist approvals': 'อนุมัติผู้ให้บริการ',
  'Dashboard access': 'สิทธิ์เข้าถึงแผงควบคุม',
  'Business profile': 'ข้อมูลธุรกิจ',
  'Loyalty program': 'โปรแกรมสะสมแต้ม',
  'Email marketing': 'การตลาดทางอีเมล',
  'Google Reviews': 'รีวิวบน Google',
  'Practice manager': 'ระบบจัดการคลินิก',
  'Quick actions': 'การดำเนินการด่วน',
  'Owner dashboard navigation': 'เมนูแผงควบคุมเจ้าของ',
  'Practice owner': 'เจ้าของคลินิก',
  'Owner account': 'บัญชีเจ้าของ',
  'Toggle dashboard menu': 'เปิดหรือปิดเมนูแผงควบคุม',
  'Owner workspace': 'พื้นที่ทำงานเจ้าของ',
  'Workspace active': 'พื้นที่ทำงานพร้อมใช้งาน',
  'Mobile owner dashboard navigation': 'เมนูแผงควบคุมเจ้าของบนมือถือ',
  'Owner dashboard': 'แผงควบคุมเจ้าของ',
  'Edit business profile': 'แก้ไขข้อมูลธุรกิจ',
  'Location': 'สถานที่',
  'Assigned branches': 'สาขาที่ได้รับมอบหมาย',
  'Practice & branch management': 'จัดการคลินิกและสาขา',
  'All branches': 'ทุกสาขา',
  '· Estimated Ontario HST': '· ภาษี HST ออนแทรีโอโดยประมาณ',
  'Active staff': 'พนักงานที่ใช้งาน',
  'Create role-limited accounts. Every account must verify sign-in with a one-time code sent to its email address.': 'สร้างบัญชีที่จำกัดสิทธิ์ตามบทบาท ทุกบัญชีต้องยืนยันการเข้าสู่ระบบด้วยรหัสใช้ครั้งเดียวที่ส่งไปยังอีเมล',
  'Name': 'ชื่อ',
  'Email': 'อีเมล',
  'Initial password (at least 12 characters)': 'รหัสผ่านเริ่มต้น (อย่างน้อย 12 ตัวอักษร)',
  'Role': 'บทบาท',
  'Owner': 'เจ้าของ',
  'Branch manager': 'ผู้จัดการสาขา',
  'Branch receptionist': 'พนักงานต้อนรับสาขา',
  'Creating…': 'กำลังสร้าง…',
  'Create dashboard account': 'สร้างบัญชีแผงควบคุม',
  'The owner sets the initial password. Share it separately through a secure channel; the account’s email is used for sign-in and OTP delivery.': 'เจ้าของเป็นผู้ตั้งรหัสผ่านเริ่มต้น กรุณาส่งรหัสผ่านแยกผ่านช่องทางที่ปลอดภัย อีเมลของบัญชีใช้เข้าสู่ระบบและรับรหัส OTP',
  'Staff accounts': 'บัญชีพนักงาน',
  'Refresh': 'รีเฟรช',
  'Disable access': 'ระงับสิทธิ์',
  'Restore access': 'คืนสิทธิ์',
  'No staff accounts have been created.': 'ยังไม่มีบัญชีพนักงาน',
  'Loading...': 'กำลังโหลด...',
  'Loading…': 'กำลังโหลด…',
  'Refresh from database': 'รีเฟรชจากฐานข้อมูล',
  'Ref ID': 'เลขอ้างอิง',
  'Customer': 'ลูกค้า',
  'Service': 'บริการ',
  'Therapist': 'ผู้ให้บริการ',
  'Time': 'เวลา',
  'Database': 'ฐานข้อมูล',
  'Total': 'ยอดรวม',
  'Actions': 'การดำเนินการ',
  'Team note:': 'หมายเหตุสำหรับทีม:',
  'Synced': 'ซิงค์แล้ว',
  'Local Only': 'เฉพาะในอุปกรณ์',
  'Removing...': 'กำลังลบ...',
  'Clear': 'ล้าง',
  'Live appointments and quick manual booking.': 'นัดหมายแบบเรียลไทม์และบันทึกการจองด่วน',
  'Search appointments': 'ค้นหานัดหมาย',
  'Calendar view': 'มุมมองปฏิทิน',
  'Daily': 'รายวัน',
  'Agenda': 'รายการนัดหมาย',
  'Calendar filters': 'ตัวกรองปฏิทิน',
  'Calendar settings': 'ตั้งค่าปฏิทิน',
  'Auto-refresh every 15 seconds': 'รีเฟรชอัตโนมัติทุก 15 วินาที',
  'Show therapist legend': 'แสดงคำอธิบายสีผู้ให้บริการ',
  'Manage ▾': 'จัดการ ▾',
  'Appointments': 'นัดหมาย',
  'Staff availability': 'เวลาว่างของพนักงาน',
  'Services': 'บริการ',
  'Add ▾': 'เพิ่ม ▾',
  'Quick Sale': 'บันทึกด่วน',
  'Quick appointment · no payment': 'นัดหมายด่วน · ยังไม่รับชำระเงิน',
  'Appointment': 'นัดหมาย',
  'Blocked staff time': 'ช่วงเวลาที่พนักงานไม่ว่าง',
  'Create New Service': 'สร้างบริการใหม่',
  'Date': 'วันที่',
  'Branch': 'สาขา',
  'All therapists': 'ผู้ให้บริการทุกคน',
  'Filters:': 'ตัวกรอง:',
  'Calendar access warning:': 'คำเตือนการเข้าถึงปฏิทิน:',
  'Blocked / unavailable this day': 'ช่วงเวลาที่ปิดรับจอง / ไม่ว่างในวันนี้',
  'Business-wide': 'ทั้งธุรกิจ',
  'Open the primary Google Calendar': 'เปิด Google Calendar หลัก',
  'MY THAI THAI · live primary calendar view': 'MY THAI THAI · มุมมองปฏิทินหลักแบบเรียลไทม์',
  '+ Book': '+ จอง',
  'Business-wide unavailable': 'ปิดรับจองทั้งธุรกิจ',
  'Couple massage': 'นวดคู่',
  'Cancelled': 'ยกเลิกแล้ว',
  'Updates automatically every 15 seconds while this tab is visible.': 'อัปเดตอัตโนมัติทุก 15 วินาทีขณะเปิดแท็บนี้',
  'Auto-refresh is paused. Use Refresh to load current appointments.': 'หยุดรีเฟรชอัตโนมัติแล้ว กดรีเฟรชเพื่อโหลดนัดหมายล่าสุด',
  'The daily view and appointment list use the same search, date, branch, and therapist filters.': 'มุมมองรายวันและรายการนัดหมายใช้ตัวกรองการค้นหา วันที่ สาขา และผู้ให้บริการเดียวกัน',
  'Therapists:': 'ผู้ให้บริการ:',
  'Any Available': 'ผู้ให้บริการที่ว่าง',
  'No appointments match this date, search, branch and therapist. Adjust your filters or add an appointment.': 'ไม่พบนัดหมายตามวันที่ การค้นหา สาขา และผู้ให้บริการที่เลือก กรุณาปรับตัวกรองหรือเพิ่มนัดหมาย',
  'Open appointment': 'เปิดนัดหมาย',
  'Add, edit, deactivate, or remove services. Changes appear on the booking portal immediately after saving.': 'เพิ่ม แก้ไข ปิดใช้งาน หรือลบบริการ การเปลี่ยนแปลงจะแสดงบนหน้าจองทันทีหลังบันทึก',
  'Tax rate': 'อัตราภาษี',
  'Active': 'ใช้งาน',
  'Description': 'คำอธิบาย',
  'Saving…': 'กำลังบันทึก…',
  'Save services': 'บันทึกบริการ',
  'Add, edit, or deactivate locations. Changes appear on the booking portal immediately after saving.': 'เพิ่ม แก้ไข หรือปิดใช้งานสาขา การเปลี่ยนแปลงจะแสดงบนหน้าจองทันทีหลังบันทึก',
  'Add branch': 'เพิ่มสาขา',
  'Branch name': 'ชื่อสาขา',
  'Street address': 'ที่อยู่',
  'City, Province': 'เมือง จังหวัด',
  'Phone': 'โทรศัพท์',
  'Customer payment choices (enable at least one)': 'วิธีชำระเงินสำหรับลูกค้า (เปิดใช้งานอย่างน้อยหนึ่งวิธี)',
  'Save branches': 'บันทึกสาขา',
  "Block off business-wide closures or a single therapist's breaks/time off. Blocks automatically stop new bookings and show up on the Booking Calendar and in the therapist portal.": 'กำหนดวันปิดของทั้งธุรกิจหรือเวลาพัก/วันลาของผู้ให้บริการ ช่วงเวลาที่กำหนดจะหยุดรับจองใหม่โดยอัตโนมัติและแสดงในปฏิทินการจองและหน้าผู้ให้บริการ',
  'Scope': 'ขอบเขต',
  'Business-wide closure': 'ปิดทั้งธุรกิจ',
  'Single therapist': 'ผู้ให้บริการรายบุคคล',
  'Branch (optional)': 'สาขา (ไม่บังคับ)',
  'Select therapist': 'เลือกผู้ให้บริการ',
  'Start time': 'เวลาเริ่ม',
  'End time': 'เวลาสิ้นสุด',
  'Reason (optional)': 'เหตุผล (ไม่บังคับ)',
  'Holiday closure, staff training, break…': 'ปิดวันหยุด อบรมพนักงาน พัก…',
  'Add block': 'เพิ่มช่วงเวลาปิดรับจอง',
  'Scheduled blocks': 'ช่วงเวลาปิดรับจองที่กำหนด',
  'Remove': 'ลบ',
  'No blocks scheduled.': 'ยังไม่มีช่วงเวลาปิดรับจอง',
  'Manage registered therapists, credentials, and which branch each therapist works at on each day of the week — supports rotation between branches. Changes sync to the booking portal and the therapist portal.': 'จัดการผู้ให้บริการ คุณวุฒิ และสาขาที่แต่ละคนทำงานในแต่ละวัน รองรับการหมุนเวียนระหว่างสาขา ข้อมูลจะซิงค์ไปยังหน้าจองและหน้าผู้ให้บริการ',
  'Full Name *': 'ชื่อเต็ม *',
  'e.g. Somsak P., RMT': 'เช่น สมศักดิ์ พ., RMT',
  'Rating (1.0 - 5.0)': 'คะแนน (1.0 - 5.0)',
  'Professional Bio / Specialty': 'ประวัติการทำงาน / ความเชี่ยวชาญ',
  'e.g. 8+ years deep tissue and Wat Pho traditional practitioner': 'เช่น ประสบการณ์กว่า 8 ปีด้านนวดกล้ามเนื้อชั้นลึกและนวดแผนไทยวัดโพธิ์',
  'Traditional Thai Certified': 'ได้รับการรับรองนวดแผนไทย',
  'RMT Healthcare Certified (Ontario CMTO)': 'ได้รับการรับรอง RMT (CMTO ออนแทรีโอ)',
  'Branch rotation — pick which branch this therapist works at on each day (leave "Off" if they don\'t work that day)': 'ตารางหมุนเวียนสาขา — เลือกสาขาที่ผู้ให้บริการทำงานในแต่ละวัน (เลือก "หยุด" หากไม่ทำงาน)',
  'Off': 'หยุด',
  'No therapists listed. Click "': 'ยังไม่มีผู้ให้บริการ กด "',
  '" above to register staff members.': '" ด้านบนเพื่อลงทะเบียนพนักงาน',
  'Save therapists & rotation': 'บันทึกผู้ให้บริการและตารางหมุนเวียน',
  'Reward your regulars': 'มอบสิทธิพิเศษให้ลูกค้าประจำ',
  'MY THAI THAI Rewards': 'สิทธิพิเศษ MY THAI THAI',
  'Manage member tiers, award points for completed visits, and record in-clinic reward redemptions.': 'จัดการระดับสมาชิก ให้แต้มสำหรับการรับบริการที่เสร็จสิ้น และบันทึกการแลกสิทธิพิเศษในคลินิก',
  'Loading loyalty members and rewards…': 'กำลังโหลดสมาชิกและสิทธิพิเศษ…',
  'Program settings': 'ตั้งค่าโปรแกรม',
  'Configure Standard, Gold and Platinum benefits. Point awards use service amounts actually paid, and existing ledger entries are unchanged.': 'กำหนดสิทธิประโยชน์ Standard, Gold และ Platinum การให้แต้มใช้ยอดค่าบริการที่ชำระจริง โดยไม่เปลี่ยนรายการบัญชีเดิม',
  'Program accepting members': 'เปิดรับสมาชิก',
  'Standard points per $1 paid': 'แต้ม Standard ต่อการชำระ $1',
  'First single-session multiplier': 'ตัวคูณแต้มสำหรับบริการครั้งแรก',
  'Points per reward': 'แต้มต่อสิทธิพิเศษ',
  'Reward value ($)': 'มูลค่าสิทธิพิเศษ ($)',
  'Gold monthly': 'Gold รายเดือน',
  'Monthly fee ($)': 'ค่าสมาชิกรายเดือน ($)',
  'Service discount (%)': 'ส่วนลดบริการ (%)',
  'Points multiplier': 'ตัวคูณแต้ม',
  'Free Hot Stone add-ons / month': 'บริการเสริมหินร้อนฟรี / เดือน',
  'Platinum company top-up': 'เติมเงินบริษัท Platinum',
  'Top-up price ($)': 'ราคาเติมเงิน ($)',
  'Prepaid hours': 'ชั่วโมงที่ชำระล่วงหน้า',
  'Hot Stone add-on discount ($)': 'ส่วนลดบริการเสริมหินร้อน ($)',
  'Charged only when a Platinum member adds the Hot Stone add-on to a booking.': 'เรียกเก็บเฉพาะเมื่อสมาชิก Platinum เพิ่มบริการเสริมหินร้อนในการจอง',
  'Platinum Hot Stone surcharge ($)': 'ค่าบริการเสริมหินร้อน Platinum ($)',
  'Company employees are matched by their enrolled email and optional company ID. Record a confirmed top-up from the member row; completed visits consume their service duration from the hours balance.': 'จับคู่พนักงานบริษัทด้วยอีเมลที่ลงทะเบียนและรหัสบริษัท (ถ้ามี) บันทึกการเติมเงินที่ยืนยันแล้วจากแถวสมาชิก บริการที่เสร็จสิ้นจะหักเวลาจากยอดชั่วโมงคงเหลือ',
  'Member tiers': 'ระดับสมาชิก',
  'Tier level is based on lifetime points earned. The first tier must begin at 0 points.': 'ระดับสมาชิกอิงจากแต้มสะสมตลอดอายุสมาชิก ระดับแรกต้องเริ่มที่ 0 แต้ม',
  'Add tier': 'เพิ่มระดับ',
  'Tier': 'ระดับ',
  'name': 'ชื่อ',
  'Tier name': 'ชื่อระดับ',
  'points threshold': 'เกณฑ์แต้ม',
  'Points threshold': 'เกณฑ์แต้ม',
  'Example reward:': 'ตัวอย่างสิทธิพิเศษ:',
  'points = $': 'แต้ม = $',
  'off in clinic.': 'ส่วนลดในคลินิก',
  'Save program settings': 'บันทึกการตั้งค่าโปรแกรม',
  'Onboard a member': 'ลงทะเบียนสมาชิก',
  "Find a recent customer by name, email or phone. For Platinum, use the employee's work email, add the company and ID, then optionally confirm the initial payment and add the configured hours in this same step.": 'ค้นหาลูกค้าล่าสุดด้วยชื่อ อีเมล หรือโทรศัพท์ สำหรับ Platinum ใช้อีเมลที่ทำงาน เพิ่มบริษัทและรหัส แล้วเลือกยืนยันการชำระเงินครั้งแรกและเพิ่มชั่วโมงในขั้นตอนเดียวกันได้',
  'Find a booking customer by name, email or phone': 'ค้นหาลูกค้าที่จองด้วยชื่อ อีเมล หรือโทรศัพท์',
  'Find a customer to enroll': 'ค้นหาลูกค้าเพื่อลงทะเบียน',
  'No booking customer matches that search.': 'ไม่พบลูกค้าตามคำค้นหา',
  'Member name': 'ชื่อสมาชิก',
  'Phone (optional)': 'โทรศัพท์ (ไม่บังคับ)',
  'Membership type': 'ประเภทสมาชิก',
  'Standard · Free points': 'Standard · สะสมแต้มฟรี',
  'Gold · Monthly': 'Gold · รายเดือน',
  'Platinum · Company top-up': 'Platinum · เติมเงินบริษัท',
  'Company name': 'ชื่อบริษัท',
  'Company ID (optional if using work email)': 'รหัสบริษัท (ไม่บังคับหากใช้อีเมลที่ทำงาน)',
  'Company registration/contact email': 'อีเมลลงทะเบียน/ติดต่อบริษัท',
  'Company contact email': 'อีเมลติดต่อบริษัท',
  'Primary owner/contact:': 'เจ้าของ/ผู้ติดต่อหลัก:',
  "this person's own top-ups fund the one shared prepaid-hour balance for": 'การเติมเงินของบุคคลนี้จะเพิ่มยอดชั่วโมงที่ชำระล่วงหน้าร่วมกันสำหรับ',
  'this company': 'บริษัทนี้',
  '. Every employee draws from that same pool — leave unchecked for a regular employee (they cannot be topped up directly).': ' พนักงานทุกคนใช้ยอดชั่วโมงเดียวกัน ไม่ต้องเลือกสำหรับพนักงานทั่วไป (ไม่สามารถเติมเงินโดยตรงได้)',
  'Payment confirmed:': 'ยืนยันการชำระเงิน:',
  'record the configured $': 'บันทึกยอดที่ตั้งไว้ $',
  'top-up and add': 'เติมเงินและเพิ่ม',
  'hours now.': 'ชั่วโมงทันที',
  'Only the primary owner/contact can be topped up.': 'เติมเงินได้เฉพาะเจ้าของ/ผู้ติดต่อหลัก',
  'Leave unchecked for a pending company claim.': 'ไม่ต้องเลือกหากยังรอยืนยันบริษัท',
  'Paid through': 'ชำระถึงวันที่',
  'Saving membership…': 'กำลังบันทึกสมาชิก…',
  'Enroll & record paid top-up': 'ลงทะเบียนและบันทึกการเติมเงินที่ชำระแล้ว',
  'Save member & email details': 'บันทึกสมาชิกและส่งรายละเอียดทางอีเมล',
  'Confirm completed visits': 'ยืนยันการรับบริการที่เสร็จสิ้น',
  'Confirm completed, paid member visits, redeem a Gold monthly Hot Stone add-on, or consume Platinum prepaid hours. Each visit can only be recorded once.': 'ยืนยันบริการของสมาชิกที่เสร็จสิ้นและชำระแล้ว ใช้บริการเสริมหินร้อนรายเดือน Gold หรือหักชั่วโมง Platinum แต่ละการรับบริการบันทึกได้เพียงครั้งเดียว',
  'Member': 'สมาชิก',
  'Visit': 'การรับบริการ',
  'Paid': 'ชำระแล้ว',
  'Points': 'แต้ม',
  'Action': 'การดำเนินการ',
  'Free add-on': 'บริการเสริมฟรี',
  'First session ·': 'บริการครั้งแรก ·',
  'Awarding…': 'กำลังให้แต้ม…',
  'Confirm & award': 'ยืนยันและให้แต้ม',
  'No completed member visits or benefits are waiting to be recorded.': 'ไม่มีบริการหรือสิทธิประโยชน์ของสมาชิกที่รอบันทึก',
  'Members & balances': 'สมาชิกและยอดคงเหลือ',
  'Search by member, email, phone, company or company ID; check eligibility, record top-ups and redeem points.': 'ค้นหาด้วยสมาชิก อีเมล โทรศัพท์ บริษัท หรือรหัสบริษัท ตรวจสอบสิทธิ์ บันทึกการเติมเงิน และแลกแต้ม',
  'Filter members by membership type': 'กรองสมาชิกตามประเภท',
  'All memberships': 'สมาชิกทุกประเภท',
  'Gold': 'โกลด์',
  'Platinum company': 'บริษัทแพลทินัม',
  'Legacy Silver': 'ซิลเวอร์เดิม',
  'Standard points': 'แต้มมาตรฐาน',
  'Search member or company': 'ค้นหาสมาชิกหรือบริษัท',
  'Search loyalty members': 'ค้นหาสมาชิกสะสมแต้ม',
  'Membership': 'สมาชิก',
  'Eligibility': 'สิทธิ์',
  'Balance': 'ยอดคงเหลือ',
  'Lifetime earned': 'แต้มสะสมตลอดอายุสมาชิก',
  'Platinum · Company': 'Platinum · บริษัท',
  'Legacy Silver · Corporate': 'Silver เดิม · บริษัท',
  'Primary contact': 'ผู้ติดต่อหลัก',
  'Points program': 'โปรแกรมสะสมแต้ม',
  'Top-up required': 'ต้องเติมเงิน',
  'shared prepaid hours remain · $': 'ชั่วโมงชำระล่วงหน้าร่วมกันคงเหลือ · $',
  'off Hot Stone add-on': 'ส่วนลดบริการเสริมหินร้อน',
  'Payment required': 'ต้องชำระเงิน',
  'Paid through:': 'ชำระถึงวันที่:',
  'not recorded': 'ยังไม่บันทึก',
  'available': 'ใช้ได้',
  'used': 'ใช้แล้ว',
  'pts': 'แต้ม',
  'hrs shared': 'ชั่วโมงร่วมกัน',
  'Redeem points': 'แลกแต้ม',
  'Record top-up': 'บันทึกการเติมเงิน',
  'Make primary contact': 'ตั้งเป็นผู้ติดต่อหลัก',
  'Record payment': 'บันทึกการชำระเงิน',
  'Copying…': 'กำลังคัดลอก…',
  'Copy portal link': 'คัดลอกลิงก์สมาชิก',
  'Copy employee signup link': 'คัดลอกลิงก์ลงทะเบียนพนักงาน',
  'Remove member': 'ลบสมาชิก',
  'Remove company': 'ลบบริษัท',
  'No members match your search.': 'ไม่พบสมาชิกตามคำค้นหา',
  'No members yet. Customers can join Rewards during online booking.': 'ยังไม่มีสมาชิก ลูกค้าสมัครโปรแกรมสะสมแต้มได้ระหว่างจองออนไลน์',
  'Recent rewards activity': 'กิจกรรมสิทธิพิเศษล่าสุด',
  'Reset ledger': 'รีเซ็ตบัญชี',
  'No reward activity recorded yet.': 'ยังไม่บันทึกกิจกรรมสิทธิพิเศษ',
  'In-clinic reward': 'สิทธิพิเศษในคลินิก',
  'Close redemption dialog': 'ปิดหน้าต่างแลกแต้ม',
  'Available:': 'ใช้ได้:',
  'points': 'แต้ม',
  '. Every': ' ทุก',
  'points gives $': 'แต้มได้รับ $',
  'off. Choose the paid booking below; the discount will be linked to its receipt number when staff issue the receipt.': 'ส่วนลด เลือกการจองที่ชำระแล้วด้านล่าง ส่วนลดจะเชื่อมกับเลขใบเสร็จเมื่อพนักงานออกใบเสร็จ',
  'Points to redeem': 'แต้มที่จะแลก',
  'Paid booking / receipt to apply the discount to': 'การจองที่ชำระแล้ว / ใบเสร็จที่จะใช้ส่วนลด',
  'Discount to apply': 'ส่วนลดที่จะใช้',
  'Cancel': 'ยกเลิก',
  'Recording…': 'กำลังบันทึก…',
  'Confirm redemption': 'ยืนยันการแลกแต้ม',
  'External payment record': 'บันทึกการชำระเงินภายนอก',
  'Record membership payment': 'บันทึกค่าสมาชิก',
  'Close payment dialog': 'ปิดหน้าต่างชำระเงิน',
  'Record the date through which the payment was received.': 'บันทึกวันที่สิ้นสุดของช่วงเวลาที่ได้รับการชำระเงิน',
  'This updates all employees onboarded under this corporate account and emails each one.': 'อัปเดตพนักงานทุกคนในบัญชีบริษัทนี้และส่งอีเมลให้แต่ละคน',
  'This activates the member discount and emails a payment confirmation.': 'เปิดใช้ส่วนลดสมาชิกและส่งอีเมลยืนยันการชำระเงิน',
  'Record payment & notify': 'บันทึกการชำระเงินและแจ้ง',
  'Confirm external payment': 'ยืนยันการชำระเงินภายนอก',
  'Record Platinum top-up': 'บันทึกการเติมเงิน Platinum',
  'Close Platinum top-up dialog': 'ปิดหน้าต่างเติมเงิน Platinum',
  'Only continue after confirming receipt of': 'ดำเนินการต่อเมื่อยืนยันว่าได้รับเงิน',
  '. This adds': ' ซึ่งจะเพิ่ม',
  'prepaid hours': 'ชั่วโมงชำระล่วงหน้า',
  'to': 'ให้',
  'the employee account': 'บัญชีพนักงาน',
  '; completed sessions deduct their duration.': ' โดยบริการที่เสร็จสิ้นจะหักเวลาที่ใช้',
  'Payment received · add hours': 'ได้รับเงินแล้ว · เพิ่มชั่วโมง',
  'Remove from loyalty program': 'นำออกจากโปรแกรมสะสมแต้ม',
  'Close remove member dialog': 'ปิดหน้าต่างลบสมาชิก',
  'This immediately removes the member from the loyalty program. Their points/hours balance and membership benefits will no longer apply. This does not affect past receipts. They will be emailed a notice.': 'นำสมาชิกออกจากโปรแกรมสะสมแต้มทันที แต้ม/ชั่วโมงและสิทธิประโยชน์จะใช้ไม่ได้ ไม่กระทบใบเสร็จเดิม และจะส่งอีเมลแจ้งสมาชิก',
  'Removing…': 'กำลังลบ…',
  'Manual reset': 'รีเซ็ตด้วยตนเอง',
  'Clear loyalty ledger': 'ล้างบัญชีสะสมแต้ม',
  'Deletes recorded points, prepaid hours and redemptions.': 'ลบแต้ม ชั่วโมงชำระล่วงหน้า และการแลกสิทธิพิเศษที่บันทึกไว้',
  'Close reset ledger dialog': 'ปิดหน้าต่างรีเซ็ตบัญชี',
  'Select a member…': 'เลือกสมาชิก…',
  'Type CLEAR LEDGER to confirm': 'พิมพ์ CLEAR LEDGER เพื่อยืนยัน',
  'This permanently deletes every ledger entry for every member. All point balances and Platinum prepaid hours reset to zero. Members themselves are not removed, and past receipts are unaffected. This cannot be undone.': 'ลบรายการบัญชีของสมาชิกทุกคนอย่างถาวร แต้มและชั่วโมง Platinum จะเป็นศูนย์ ไม่ลบสมาชิกและไม่กระทบใบเสร็จเดิม ไม่สามารถย้อนกลับได้',
  'This permanently deletes every ledger entry for the selected member. Their point balance and Platinum prepaid hours reset to zero. Their membership stays active and past receipts are unaffected. This cannot be undone.': 'ลบรายการบัญชีของสมาชิกที่เลือกอย่างถาวร แต้มและชั่วโมง Platinum จะเป็นศูนย์ สมาชิกยังใช้งานได้และไม่กระทบใบเสร็จเดิม ไม่สามารถย้อนกลับได้',
  'Clearing…': 'กำลังล้าง…',
  'Clear entire ledger': 'ล้างบัญชีทั้งหมด',
  'Clear member ledger': 'ล้างบัญชีสมาชิก',
  'Remove corporate account': 'ลบบัญชีบริษัท',
  'Remove all members from': 'ลบสมาชิกทั้งหมดจาก',
  'Close remove company dialog': 'ปิดหน้าต่างลบบริษัท',
  'This removes every Platinum or Legacy Silver employee enrolled under': 'นำพนักงาน Platinum หรือ Silver เดิมทุกคนที่ลงทะเบียนภายใต้',
  'from the loyalty program. Each employee will be emailed a removal notice (with the company contact copied, if one is on file). This does not affect past receipts.': 'ออกจากโปรแกรมสะสมแต้ม พนักงานแต่ละคนจะได้รับอีเมลแจ้งการลบ (สำเนาถึงผู้ติดต่อบริษัทหากมี) ไม่กระทบใบเสร็จเดิม',
  'Grow your practice': 'เติบโตธุรกิจของคุณ',
  'Google Ads performance': 'ผลการโฆษณา Google Ads',
  'Explore campaign results over a date range you choose.': 'ดูผลแคมเปญตามช่วงวันที่ที่เลือก',
  'Refresh report': 'รีเฟรชรายงาน',
  'Open Google Ads': 'เปิด Google Ads',
  'From': 'จากวันที่',
  'To': 'ถึงวันที่',
  'Apply range': 'ใช้ช่วงวันที่',
  'Quick range': 'ช่วงวันที่ด่วน',
  'Last': 'ย้อนหลัง',
  'days': 'วัน',
  'Connecting securely to Google Ads…': 'กำลังเชื่อมต่อ Google Ads อย่างปลอดภัย…',
  'Google Ads reporting is unavailable. Check the server integration settings and refresh.': 'รายงาน Google Ads ไม่พร้อมใช้งาน กรุณาตรวจสอบการเชื่อมต่อบนเซิร์ฟเวอร์แล้วรีเฟรช',
  'Account': 'บัญชี',
  'Connected': 'เชื่อมต่อแล้ว',
  'Campaigns': 'แคมเปญ',
  'Search, filter and sort results for the selected reporting period.': 'ค้นหา กรอง และเรียงผลลัพธ์สำหรับช่วงรายงานที่เลือก',
  'of': 'จาก',
  'campaigns': 'แคมเปญ',
  'Search campaigns': 'ค้นหาแคมเปญ',
  'Campaign status': 'สถานะแคมเปญ',
  'All statuses': 'ทุกสถานะ',
  'Enabled': 'เปิดใช้งาน',
  'Paused': 'หยุดชั่วคราว',
  'Sort campaigns by': 'เรียงแคมเปญตาม',
  'Sort: Impressions': 'เรียง: จำนวนการแสดงผล',
  'Sort: Clicks': 'เรียง: จำนวนคลิก',
  'Sort: Spend': 'เรียง: ค่าใช้จ่าย',
  'Sort: Conversions': 'เรียง: คอนเวอร์ชัน',
  'Sort: Name': 'เรียง: ชื่อ',
  'Campaign': 'แคมเปญ',
  'Status': 'สถานะ',
  'Impressions': 'จำนวนการแสดงผล',
  'Clicks': 'จำนวนคลิก',
  'Spend': 'ค่าใช้จ่าย',
  'Conversions': 'คอนเวอร์ชัน',
  'ID': 'รหัส',
  'No campaigns match the current search and filters.': 'ไม่พบแคมเปญตามคำค้นหาและตัวกรอง',
  'No campaigns were returned for the selected dates.': 'ไม่พบแคมเปญในช่วงวันที่ที่เลือก',
  'Reporting is read-only. Create, edit, and manage budgets from Google Ads. Metrics are provided by Google Ads and may be delayed.': 'รายงานนี้ดูได้อย่างเดียว สร้าง แก้ไข และจัดการงบประมาณผ่าน Google Ads ตัวชี้วัดจาก Google Ads อาจแสดงล่าช้า',
  'See your latest Google Business Profile reviews and rating at a glance.': 'ดูรีวิวและคะแนนล่าสุดของ Google Business Profile',
  'Ask for a review': 'ขอรีวิว',
  'View on Google': 'ดูบน Google',
  'Fetching your Google reviews…': 'กำลังโหลดรีวิวจาก Google…',
  'Google Reviews are not connected yet. Add': 'ยังไม่ได้เชื่อมต่อรีวิว Google เพิ่ม',
  'and': 'และ',
  'to the server environment, then refresh.': 'ในสภาพแวดล้อมเซิร์ฟเวอร์ แล้วรีเฟรช',
  'Average rating': 'คะแนนเฉลี่ย',
  'Total ratings': 'จำนวนผู้ให้คะแนน',
  'Business': 'ธุรกิจ',
  'Not available': 'ไม่มีข้อมูล',
  'Most recent reviews': 'รีวิวล่าสุด',
  'Google surfaces up to 5 recent reviews through the Places API.': 'Google แสดงรีวิวล่าสุดสูงสุด 5 รายการผ่าน Places API',
  'No reviews are available yet.': 'ยังไม่มีรีวิว',
  'Reviews are read-only and refresh from Google every few minutes. Use "Ask for a review" to email past customers a link to your Google review form.': 'รีวิวดูได้อย่างเดียวและรีเฟรชจาก Google ทุกไม่กี่นาที ใช้ "ขอรีวิว" เพื่อส่งลิงก์แบบฟอร์มรีวิว Google ให้ลูกค้าเดิมทางอีเมล',
  'Ask past customers for a review': 'ขอรีวิวจากลูกค้าเดิม',
  'Emails a Google review link to customers who have already attended an appointment': 'ส่งลิงก์รีวิว Google ทางอีเมลให้ลูกค้าที่เคยรับบริการแล้ว',
  'Finding customers who have visited…': 'กำลังค้นหาลูกค้าที่เคยรับบริการ…',
  'No completed visits to ask yet.': 'ยังไม่มีลูกค้าที่รับบริการเสร็จเพื่อขอรีวิว',
  'Checked': 'ตรวจสอบแล้ว',
  'booking': 'การจอง',
  's': '',
  'not finished yet,': 'ยังไม่เสร็จสิ้น,',
  'cancelled,': 'ยกเลิกแล้ว,',
  'without a valid email,': 'ไม่มีอีเมลที่ถูกต้อง,',
  'older than': 'เกิน',
  'days. A customer appears here once their appointment end time has passed.': 'วัน ลูกค้าจะแสดงที่นี่เมื่อพ้นเวลาสิ้นสุดนัดหมาย',
  'selected': 'เลือกแล้ว',
  'Select all': 'เลือกทั้งหมด',
  'Last visit': 'รับบริการล่าสุด',
  'Unsubscribed from emails': 'ยกเลิกรับอีเมลแล้ว',
  'Already asked on': 'ขอรีวิวแล้วเมื่อ',
  'Sending…': 'กำลังส่ง…',
  'Build an audience with chat, review your message, and send from mythaithaimassage@gmail.com.': 'เลือกกลุ่มผู้รับด้วยแชต ตรวจสอบข้อความ และส่งจาก mythaithaimassage@gmail.com',
  'Campaigns go only to people who checked the optional marketing consent box when booking and remain subscribed. Each email includes an unsubscribe link. Appointment confirmations and receipts are separate.': 'แคมเปญส่งเฉพาะผู้ที่ยินยอมรับการตลาดขณะจองและยังสมัครรับอีเมล อีเมลทุกฉบับมีลิงก์ยกเลิกการรับอีเมล ไม่รวมอีเมลยืนยันนัดหมายและใบเสร็จ',
  'Audience assistant': 'ผู้ช่วยเลือกกลุ่มผู้รับ',
  'Describe a segment in your own words, or switch to manual filters to pick it yourself. The list is rebuilt from the live database every time, so deleted customers are removed automatically. Gemini only ever receives your description and the branch, service, and membership names — never customer or patient data.': 'อธิบายกลุ่มผู้รับหรือใช้ตัวกรองด้วยตนเอง ระบบสร้างรายชื่อจากฐานข้อมูลล่าสุดทุกครั้งและนำลูกค้าที่ลบออกโดยอัตโนมัติ Gemini ได้รับเฉพาะคำอธิบายและชื่อสาขา บริการ และสมาชิก ไม่ได้รับข้อมูลลูกค้า',
  'matched /': 'ตรงเงื่อนไข /',
  'opted in': 'ยินยอมรับอีเมล',
  'Checking opted-in contacts and booking history…': 'กำลังตรวจสอบรายชื่อผู้ยินยอมและประวัติการจอง…',
  'e.g. All active opted-in subscribers': 'เช่น ผู้รับอีเมลที่ยินยอมและใช้งานทุกคน',
  'Thinking…': 'กำลังประมวลผล…',
  'Find audience': 'ค้นหากลุ่มผู้รับ',
  'Any membership': 'สมาชิกทุกประเภท',
  'Any branch': 'ทุกสาขา',
  'Any service': 'ทุกบริการ',
  'Visits on a weekday': 'วันในสัปดาห์ที่รับบริการ',
  'Any day': 'ทุกวัน',
  'Booked in the last (days)': 'จองภายในช่วงย้อนหลัง (วัน)',
  'e.g. 30': 'เช่น 30',
  'Most recent customers': 'ลูกค้าล่าสุด',
  'e.g. 20': 'เช่น 20',
  'Only regulars (two or more visits that weekday)': 'เฉพาะลูกค้าประจำ (รับบริการในวันนั้นอย่างน้อยสองครั้ง)',
  'All active opted-in subscribers': 'ผู้รับอีเมลที่ยินยอมและใช้งานทุกคน',
  'Manual filters run entirely on your own data — nothing is sent to an AI service.': 'ตัวกรองด้วยตนเองใช้เฉพาะข้อมูลของคุณ ไม่มีข้อมูลส่งไปยังบริการ AI',
  'Clear filters': 'ล้างตัวกรอง',
  'Matching…': 'กำลังค้นหา…',
  'No opted-in subscribers match that description yet.': 'ยังไม่มีผู้ยินยอมรับอีเมลตรงกับคำอธิบาย',
  'There are no opted-in subscribers yet. New customers can choose marketing emails in the booking form.': 'ยังไม่มีผู้ยินยอมรับอีเมล ลูกค้าใหม่เลือกสมัครอีเมลการตลาดได้ในแบบฟอร์มจอง',
  'This filter matches': 'ตัวกรองนี้ตรงกับ',
  'active opted-in subscribers. A branch, weekday, or date filter requires a matching booking in the history. Choose “All active opted-in subscribers” above to include everyone.': 'ผู้รับอีเมลที่ยินยอมและใช้งาน ตัวกรองสาขา วันในสัปดาห์ หรือวันที่ต้องมีประวัติการจองที่ตรงกัน เลือก “ผู้รับอีเมลที่ยินยอมและใช้งานทุกคน” ด้านบนเพื่อรวมทุกคน',
  'contact': 'รายชื่อ',
  'with no remaining customer records': 'ที่ไม่มีข้อมูลลูกค้าเหลืออยู่',
  'was': 'ถูก',
  'were': 'ถูก',
  'removed from the marketing list.': 'นำออกจากรายชื่อการตลาดแล้ว',
  'Campaigns are limited to 50 recipients per send. Narrow this group before sending.': 'ส่งแคมเปญได้สูงสุด 50 ผู้รับต่อครั้ง กรุณาลดกลุ่มผู้รับก่อนส่ง',
  'Audience matching uses historical booking dates, not verified attendance or visit frequency.': 'การจับคู่กลุ่มผู้รับใช้วันที่จองในอดีต ไม่ใช่การยืนยันการเข้ารับบริการหรือความถี่',
  'Campaign message': 'ข้อความแคมเปญ',
  'Use the writing assistant to create an editable draft, then review, save, or send it.': 'ใช้ผู้ช่วยเขียนสร้างฉบับร่างที่แก้ไขได้ แล้วตรวจสอบ บันทึก หรือส่ง',
  'What should this campaign say?': 'แคมเปญนี้ควรสื่อสารอะไร?',
  'e.g. Write a friendly note inviting this audience to take time for self-care. Do not include an offer.': 'เช่น เขียนข้อความเป็นกันเองเชิญผู้รับให้เวลาดูแลตัวเอง โดยไม่ใส่ข้อเสนอ',
  'Gemini receives only your campaign goal and the aggregate audience description—not customer names, emails, or booking rows. The generated copy is not sent until you review and confirm.': 'Gemini ได้รับเฉพาะเป้าหมายแคมเปญและคำอธิบายกลุ่มผู้รับโดยรวม ไม่ได้รับชื่อ อีเมล หรือรายการจอง ข้อความจะไม่ส่งจนกว่าคุณตรวจสอบและยืนยัน',
  'Generating…': 'กำลังสร้าง…',
  'Generate campaign': 'สร้างแคมเปญ',
  'Subject line': 'หัวเรื่อง',
  'A little time for yourself…': 'ให้เวลากับตัวเองสักนิด…',
  'Preview text': 'ข้อความตัวอย่าง',
  'A short summary shown in the inbox': 'สรุปสั้นที่แสดงในกล่องจดหมาย',
  'Message': 'ข้อความ',
  'Write a helpful, considerate message for your subscribers…': 'เขียนข้อความที่เป็นประโยชน์และใส่ใจผู้รับ…',
  '/5000 characters': '/5000 ตัวอักษร',
  'Save draft': 'บันทึกฉบับร่าง',
  'Email preview': 'ตัวอย่างอีเมล',
  'MY THAI THAI · to your subscribers': 'MY THAI THAI · ถึงผู้สมัครรับอีเมล',
  'Your campaign subject': 'หัวเรื่องแคมเปญของคุณ',
  'Preview text appears here': 'ข้อความตัวอย่างจะแสดงที่นี่',
  'Your message preview will appear here as you write.': 'ตัวอย่างข้อความจะแสดงที่นี่ขณะพิมพ์',
  'MY THAI THAI · Business mailing address from profile': 'MY THAI THAI · ที่อยู่ไปรษณีย์จากข้อมูลธุรกิจ',
  'You are receiving this because you opted in to promotional emails.': 'คุณได้รับอีเมลนี้เพราะยินยอมรับอีเมลส่งเสริมการขาย',
  'Unsubscribe': 'ยกเลิกการรับอีเมล',
  'Campaign emails include your business mailing address and an unsubscribe link. Sending requires Gmail OAuth and a mailing address in Business profile.': 'อีเมลแคมเปญมีที่อยู่ไปรษณีย์ธุรกิจและลิงก์ยกเลิกการรับอีเมล การส่งต้องใช้ Gmail OAuth และที่อยู่ในข้อมูลธุรกิจ',
  'Saved drafts': 'ฉบับร่างที่บันทึก',
  'Stored only on this device': 'จัดเก็บเฉพาะบนอุปกรณ์นี้',
  'Draft loaded for editing.': 'โหลดฉบับร่างเพื่อแก้ไขแล้ว',
  'Updated': 'อัปเดต',
  'Delete': 'ลบ',
  'No campaign drafts saved yet.': 'ยังไม่มีฉบับร่างที่บันทึก',
  'Campaign history': 'ประวัติแคมเปญ',
  'Logged to BigQuery with a campaign ID for future reference/audit': 'บันทึกใน BigQuery พร้อมรหัสแคมเปญเพื่ออ้างอิง/ตรวจสอบ',
  'Refreshing…': 'กำลังรีเฟรช…',
  'Sent': 'ส่งแล้ว',
  'Subject': 'หัวเรื่อง',
  'Audience': 'กลุ่มผู้รับ',
  'Sent / Failed': 'ส่งแล้ว / ไม่สำเร็จ',
  'Campaign ID': 'รหัสแคมเปญ',
  'failed': 'ไม่สำเร็จ',
  'Loading campaign history…': 'กำลังโหลดประวัติแคมเปญ…',
  'No campaigns sent yet.': 'ยังไม่มีแคมเปญที่ส่ง',
  'Owner settings': 'ตั้งค่าเจ้าของ',
  'Manage the identity and contact details associated with your practice.': 'จัดการข้อมูลธุรกิจและรายละเอียดการติดต่อของคลินิก',
  'Synced across owner devices': 'ซิงค์ระหว่างอุปกรณ์ของเจ้าของ',
  'Loading business profile…': 'กำลังโหลดข้อมูลธุรกิจ…',
  'The saved profile could not be loaded. Retry before making changes.': 'ไม่สามารถโหลดข้อมูลที่บันทึกได้ กรุณาลองอีกครั้งก่อนแก้ไข',
  'Retry loading': 'ลองโหลดอีกครั้ง',
  'Business name / display name': 'ชื่อธุรกิจ / ชื่อที่แสดง',
  'Legal business name': 'ชื่อธุรกิจตามกฎหมาย',
  'Short description': 'คำอธิบายสั้น',
  'Business email': 'อีเมลธุรกิจ',
  'Phone number': 'หมายเลขโทรศัพท์',
  'Website': 'เว็บไซต์',
  'Business location': 'ที่ตั้งธุรกิจ',
  'GST/HST registration number': 'เลขทะเบียน GST/HST',
  'Business photo URL': 'URL รูปภาพธุรกิจ',
  'Paste a publicly accessible image URL. Leave blank to use the business initials.': 'วาง URL รูปภาพที่เข้าถึงได้สาธารณะ เว้นว่างเพื่อใช้อักษรย่อธุรกิจ',
  'Profile details are stored in your connected database and available when you sign in on another device.': 'รายละเอียดจัดเก็บในฐานข้อมูลที่เชื่อมต่อและใช้ได้เมื่อเข้าสู่ระบบบนอุปกรณ์อื่น',
  'Save profile': 'บันทึกข้อมูลธุรกิจ',
  'Profile preview': 'ตัวอย่างข้อมูลธุรกิจ',
  'Your business name': 'ชื่อธุรกิจของคุณ',
  'Add a short introduction to your practice.': 'เพิ่มคำแนะนำคลินิกสั้น ๆ',
  'GST/HST No.': 'เลข GST/HST',
  'Therapist account approvals': 'อนุมัติบัญชีผู้ให้บริการ',
  'New therapist sign-ups appear here. Approved therapists can sign in to the therapist view.': 'ผู้ให้บริการที่สมัครใหม่แสดงที่นี่ ผู้ที่ได้รับอนุมัติเข้าสู่หน้าผู้ให้บริการได้',
  'Pending approval': 'รออนุมัติ',
  'Approved': 'อนุมัติแล้ว',
  'Rejected': 'ปฏิเสธแล้ว',
  '· Signed up': '· สมัครเมื่อ',
  'date unknown': 'ไม่ทราบวันที่',
  'Approve': 'อนุมัติ',
  'Reject': 'ปฏิเสธ',
  'Revoke access': 'เพิกถอนสิทธิ์',
  'Patient History Profiles': 'ประวัติลูกค้า',
  'Patient Summary': 'สรุปข้อมูลลูกค้า',
  'Confidential health information. Access only for authorized clinic staff.': 'ข้อมูลสุขภาพเป็นความลับ เข้าถึงได้เฉพาะพนักงานคลินิกที่ได้รับอนุญาต',
  'Search patient or booking...': 'ค้นหาลูกค้าหรือการจอง...',
  'No patient history profiles found.': 'ไม่พบประวัติลูกค้า',
  'profile(s)': 'รายการ',
  'No date': 'ไม่มีวันที่',
  'DOB not provided': 'ไม่ระบุวันเกิด',
  'Gender not provided': 'ไม่ระบุเพศ',
  'Consent:': 'ความยินยอม:',
  'Not recorded': 'ยังไม่บันทึก',
  'Clearing...': 'กำลังล้าง...',
  'Clear this record': 'ล้างรายการนี้',
  'Reported health conditions': 'ภาวะสุขภาพที่แจ้ง',
  'Contact': 'ข้อมูลติดต่อ',
  'No email': 'ไม่มีอีเมล',
  'No phone': 'ไม่มีโทรศัพท์',
  'No address': 'ไม่มีที่อยู่',
  'Treatment notes': 'บันทึกการรักษา',
  'Body areas:': 'บริเวณร่างกาย:',
  'None listed': 'ไม่ระบุ',
  'Pain/discomfort:': 'อาการปวด/ไม่สบาย:',
  'Additional details:': 'รายละเอียดเพิ่มเติม:',
  'View full medical questionnaire': 'ดูแบบสอบถามสุขภาพฉบับเต็ม',
  'Not answered': 'ไม่ได้ตอบ',
  'Business intelligence': 'ข้อมูลวิเคราะห์ธุรกิจ',
  'Track sales, collections, and appointment trends.': 'ติดตามยอดขาย การรับชำระเงิน และแนวโน้มนัดหมาย',
  'Refresh data': 'รีเฟรชข้อมูล',
  'Daily reports': 'รายงานรายวัน',
  'Therapist hours & branch audit': 'ชั่วโมงผู้ให้บริการและตรวจสอบสาขา',
  'Download a PDF of therapist hours served, or a per-branch audit of therapist working hours, for a single day.': 'ดาวน์โหลด PDF ชั่วโมงให้บริการของผู้ให้บริการ หรือรายงานตรวจสอบเวลาทำงานแยกสาขาสำหรับหนึ่งวัน',
  'Report date': 'วันที่รายงาน',
  'Therapist hours (PDF)': 'ชั่วโมงผู้ให้บริการ (PDF)',
  'Branch audit (PDF)': 'ตรวจสอบสาขา (PDF)',
  'Selected reporting period': 'ช่วงรายงานที่เลือก',
  'Payments collected': 'ยอดรับชำระเงิน',
  'Daily totals · last 7 days in this period': 'ยอดรายวัน · 7 วันล่าสุดในช่วงนี้',
  'Estimated HST collected:': 'ภาษี HST ที่จัดเก็บโดยประมาณ:',
  'Top services': 'บริการยอดนิยม',
  'By gross sales in selected period': 'ตามยอดขายรวมในช่วงที่เลือก',
  'appointment': 'นัดหมาย',
  'No sales recorded for this date range.': 'ไม่มียอดขายในช่วงวันที่นี้',
  'Recent sales': 'ยอดขายล่าสุด',
  'Appointment totals and payments received': 'ยอดนัดหมายและการชำระเงินที่ได้รับ',
  'records': 'รายการ',
  'Date / receipt': 'วันที่ / ใบเสร็จ',
  'Patient': 'ลูกค้า',
  'No bookings in this reporting period.': 'ไม่มีการจองในช่วงรายงานนี้',
  'Appointment details': 'รายละเอียดนัดหมาย',
  'Calendar event': 'กิจกรรมปฏิทิน',
  'Close appointment details': 'ปิดรายละเอียดนัดหมาย',
  'This appointment was booked directly on the calendar and was automatically linked to a new booking record.': 'นัดหมายนี้จองโดยตรงบนปฏิทินและเชื่อมกับรายการจองใหม่โดยอัตโนมัติ',
  'Add the missing details below to enable receipt issuing.': 'เพิ่มข้อมูลที่ขาดด้านล่างเพื่อออกใบเสร็จ',
  'Unassigned': 'ยังไม่มอบหมาย',
  'Reassign this appointment to another therapist': 'เปลี่ยนผู้ให้บริการสำหรับนัดหมายนี้',
  'Change therapist…': 'เปลี่ยนผู้ให้บริการ…',
  'Assign': 'มอบหมาย',
  'Only therapists who are free at this date and time can be assigned. The calendar event is updated to match.': 'มอบหมายได้เฉพาะผู้ให้บริการที่ว่างในวันและเวลานี้ กิจกรรมปฏิทินจะอัปเดตให้ตรงกัน',
  'Amount paid': 'ยอดชำระแล้ว',
  'Appointment total': 'ยอดรวมนัดหมาย',
  'Patient email': 'อีเมลลูกค้า',
  'Payment method': 'วิธีชำระเงิน',
  'Cash': 'เงินสด',
  'Card': 'บัตร',
  'E-transfer': 'โอนเงินอิเล็กทรอนิกส์',
  'Other': 'อื่น ๆ',
  'Appointment total ($)': 'ยอดรวมนัดหมาย ($)',
  'Amount paid ($)': 'ยอดชำระแล้ว ($)',
  'Save details': 'บันทึกรายละเอียด',
  'Paid already': 'ชำระแล้ว',
  'Paid already — mark as fully paid': 'ชำระแล้ว — บันทึกว่าชำระครบ',
  'Recording payment…': 'กำลังบันทึกการชำระเงิน…',
  'Full payment is recorded for this booking.': 'บันทึกการชำระครบสำหรับการจองนี้แล้ว',
  'Receipt issued': 'ออกใบเสร็จแล้ว',
  'Loyalty discount ·': 'ส่วนลดสะสมแต้ม ·',
  'Manual discount': 'ส่วนลดที่พนักงานกำหนด',
  'Total paid': 'ยอดชำระรวม',
  'Reconciliation confirmed. Booking total and paid amount synced to the database: $': 'ยืนยันการกระทบยอดแล้ว ซิงค์ยอดจองและยอดชำระลงฐานข้อมูล: $',
  'Recorded payment: $': 'ยอดชำระที่บันทึก: $',
  '. Excess recorded payment: $': ' ยอดชำระเกินที่บันทึก: $',
  '. Reconcile manually; no automatic refund has been issued.': ' กรุณากระทบยอดด้วยตนเอง ยังไม่ได้คืนเงินอัตโนมัติ',
  'Allocated prepaid value: $': 'มูลค่าชำระล่วงหน้าที่จัดสรร: $',
  '. New payment: $0.00.': ' การชำระใหม่: $0.00',
  'Loyalty balance:': 'แต้มคงเหลือ:',
  'points.': 'แต้ม',
  'Receipt email sent to': 'ส่งอีเมลใบเสร็จถึง',
  'Manual discount ($) — optional': 'ส่วนลดที่พนักงานกำหนด ($) — ไม่บังคับ',
  'An issued receipt keeps its original discount.': 'ใบเสร็จที่ออกแล้วใช้ส่วนลดเดิม',
  'Verified prepaid package allocations cannot be discounted.': 'ไม่สามารถลดราคาส่วนที่จัดสรรจากแพ็กเกจชำระล่วงหน้าที่ตรวจสอบแล้ว',
  'Deducted before HST, after membership and loyalty discounts. Leave blank for no discount. Confirm reconciliation below to update the booking total and paid amount when issuing the receipt.': 'หักก่อนภาษี HST และหลังส่วนลดสมาชิกและสะสมแต้ม เว้นว่างหากไม่มีส่วนลด ยืนยันการกระทบยอดด้านล่างเพื่ออัปเดตยอดจองและยอดชำระเมื่อออกใบเสร็จ',
  'Confirm reconciliation': 'ยืนยันการกระทบยอด',
  'I confirm any payment adjustment or refund has been handled. Issuing the receipt will save the discounted total and paid amount to the database and refresh the bookings list. No Square refund is sent automatically.': 'ฉันยืนยันว่าได้ดำเนินการปรับยอดหรือคืนเงินแล้ว การออกใบเสร็จจะบันทึกยอดหลังส่วนลดและยอดชำระลงฐานข้อมูลและรีเฟรชรายการจอง โดยไม่คืนเงินผ่าน Square อัตโนมัติ',
  'Receipts are available only after full payment is recorded.': 'ออกใบเสร็จได้หลังบันทึกการชำระครบเท่านั้น',
  'Add a valid patient email to the booking before issuing a receipt.': 'เพิ่มอีเมลลูกค้าที่ถูกต้องก่อนออกใบเสร็จ',
  'This appointment is not linked to a booking record.': 'นัดหมายนี้ยังไม่เชื่อมกับรายการจอง',
  'A receipt will be emailed to the patient and recorded with this booking.': 'ใบเสร็จจะส่งทางอีเมลให้ลูกค้าและบันทึกกับการจองนี้',
  'Issuing…': 'กำลังออกใบเสร็จ…',
  'Issue & email receipt': 'ออกและส่งใบเสร็จทางอีเมล',
  'Notes': 'หมายเหตุ',
  'Log a quick note about this appointment...': 'บันทึกหมายเหตุสั้น ๆ เกี่ยวกับนัดหมายนี้...',
  'Add note': 'เพิ่มหมายเหตุ',
  'Loading notes…': 'กำลังโหลดหมายเหตุ…',
  'No notes logged for this appointment yet.': 'ยังไม่มีหมายเหตุสำหรับนัดหมายนี้',
  'This calendar event could not be automatically linked to a booking record. Reload the calendar to try again.': 'ไม่สามารถเชื่อมกิจกรรมปฏิทินกับรายการจองโดยอัตโนมัติ กรุณาโหลดปฏิทินอีกครั้ง',
  'Print / save PDF': 'พิมพ์ / บันทึก PDF',
  'Workspace': 'พื้นที่ทำงาน',
  'Manage': 'จัดการ',
  'Grow': 'เติบโต',
  'Practice platform': 'แพลตฟอร์มจัดการคลินิก',
  'Staff platform views': 'มุมมองแพลตฟอร์มพนักงาน',
  'Booking': 'จองบริการ',
  'Dashboard': 'แผงควบคุม',
  'All rights reserved.': 'สงวนลิขสิทธิ์',
  'Legal information': 'ข้อมูลทางกฎหมาย',
  'Privacy Policy': 'นโยบายความเป็นส่วนตัว',
  'Terms of Service': 'ข้อกำหนดการใช้บริการ',
  'Historical Wix contacts': 'รายชื่อติดต่อเดิมจาก Wix',
  'Historical Wix bookings': 'การจองเดิมจาก Wix',
  'Disable dashboard access for {value0}?': 'ระงับสิทธิ์แผงควบคุมของ {value0}?',
  'Permanently remove booking {value0} and its calendar event? This cannot be undone.': 'ลบการจอง {value0} และกิจกรรมปฏิทินอย่างถาวร? ไม่สามารถย้อนกลับได้',
  'Send “{value0}” to {value1} opted-in recipients?\n\nAudience: {value2}\n\nThis sends immediately from {value3}.': 'ส่ง “{value0}” ถึงผู้รับที่ยินยอม {value1} คน?\n\nกลุ่มผู้รับ: {value2}\n\nจะส่งทันทีจาก {value3}',
  'Permanently clear the medical history on file for {value0}? This cannot be undone.': 'ล้างประวัติสุขภาพของ {value0} อย่างถาวร? ไม่สามารถย้อนกลับได้',
  'Reject the therapist account request from {value0}?': 'ปฏิเสธคำขอบัญชีผู้ให้บริการจาก {value0}?',
  'Revoke access for {value0}? They will not be able to sign in until approved again.': 'เพิกถอนสิทธิ์ของ {value0}? จะเข้าสู่ระบบไม่ได้จนกว่าจะอนุมัติอีกครั้ง',
  ' · {value0}': ' · {value0}',
  '{value0} unavailable': '{value0} ไม่ว่าง',
  '· {value0}': '· {value0}',
  ' Only the primary owner/contact can be topped up.': ' เติมเงินได้เฉพาะเจ้าของ/ผู้ติดต่อหลัก',
  ' Leave unchecked for a pending company claim.': ' ไม่ต้องเลือกหากยังรอยืนยันบริษัท',
  '+{value0} pts': '+{value0} แต้ม',
  '{value0} hrs': '{value0} ชั่วโมง',
  'x': 'เท่า',
  'Standard · {value0}': 'มาตรฐาน · {value0}',
  ' · ID {value0}': ' · รหัส {value0}',
  ' · Contact: {value0}': ' · ติดต่อ: {value0}',
  '{value0}% off active': 'ส่วนลด {value0}% ใช้งานอยู่',
  ' · Hot Stone add-on {value0} this month': ' · บริการเสริมหินร้อน {value0} ในเดือนนี้',
  ' · Booking {value0}': ' · การจอง {value0}',
  ' · Receipt {value0}': ' · ใบเสร็จ {value0}',
  '{value0}{value1} hrs': '{value0}{value1} ชั่วโมง',
  '{value0}{value1} pts': '{value0}{value1} แต้ม',
  ' in the last {value0} days': ' ในช่วง {value0} วันที่ผ่านมา',
  ' Sent from {value0}.': ' ส่งจาก {value0}',
  'Send to {value0}': 'ส่งถึง {value0}',
  'Examples: {value0}': 'ตัวอย่าง: {value0}',
  '${value0}': '${value0}',
  'Check this if payment has been received. It records ${value0} as paid and enables receipt issuing.': 'เลือกหากได้รับเงินแล้ว จะบันทึกยอดชำระ ${value0} และเปิดให้ใช้งานการออกใบเสร็จ',
  'Server returned status {value0}': 'เซิร์ฟเวอร์ตอบกลับสถานะ {value0}',
  'Unable to save branches': 'ไม่สามารถบันทึกสาขาได้',
  'Unable to save services': 'ไม่สามารถบันทึกบริการได้',
  'Unable to load the business profile': 'ไม่สามารถโหลดข้อมูลธุรกิจได้',
  'Google Ads returned status {value0}': 'Google Ads ตอบกลับสถานะ {value0}',
  'Unable to load Google Ads campaign data.': 'ไม่สามารถโหลดข้อมูลแคมเปญ Google Ads ได้',
  'Google Reviews returned status {value0}': 'รีวิว Google ตอบกลับสถานะ {value0}',
  'Unable to load Google reviews.': 'ไม่สามารถโหลดรีวิว Google ได้',
  'Unable to load customers who have visited.': 'ไม่สามารถโหลดลูกค้าที่เคยรับบริการได้',
  'Unable to send review requests.': 'ไม่สามารถส่งคำขอรีวิวได้',
  'Unable to load the loyalty program.': 'ไม่สามารถโหลดโปรแกรมสะสมแต้มได้',
  'Unable to save loyalty settings.': 'ไม่สามารถบันทึกการตั้งค่าสะสมแต้มได้',
  'Points or prepaid hours were already recorded for this booking.': 'บันทึกแต้ม หรือชั่วโมงชำระล่วงหน้าสำหรับการจองนี้แล้ว',
  'Unable to award loyalty points.': 'ไม่สามารถให้แต้มสะสมได้',
  '{value0} points redeemed for ${value1} off and linked to booking {value2}. Remaining balance: {value3} points.{value4}': 'แลก {value0} แต้มเป็นส่วนลด ${value1} และเชื่อมกับการจอง {value2} แต้มคงเหลือ: {value3} แต้ม{value4}',
  'Unable to redeem loyalty points.': 'ไม่สามารถแลกแต้มได้',
  'Unable to onboard member.': 'ไม่สามารถลงทะเบียนสมาชิกได้',
  'Unable to record Platinum top-up.': 'ไม่สามารถบันทึกการเติมเงิน Platinum ได้',
  'Recorded ${value0} payment; {value1} prepaid hours added. New balance: {value2} hours.{value3}': 'บันทึกการชำระ ${value0} เพิ่มชั่วโมงล่วงหน้า {value1} ชั่วโมง ยอดใหม่: {value2} ชั่วโมง{value3}',
  'Unable to update the primary contact.': 'ไม่สามารถอัปเดตผู้ติดต่อหลักได้',
  '{value0} is now the primary owner/contact for {value1} — only they can top up the shared balance.': '{value0} เป็นเจ้าของ/ผู้ติดต่อหลักของ {value1} แล้ว เฉพาะบุคคลนี้เท่านั้นที่เติมยอดร่วมกันได้',
  'Unable to record membership payment.': 'ไม่สามารถบันทึกค่าสมาชิกได้',
  'Payment recorded through {value0} for {value1} member(s).{value2}': 'บันทึกการชำระถึงวันที่ {value0} สำหรับสมาชิก {value1} คน{value2}',
  'Unable to remove this member.': 'ไม่สามารถลบสมาชิกนี้ได้',
  '{value0} was removed from the loyalty program.{value1}': 'นำ {value0} ออกจากโปรแกรมสะสมแต้มแล้ว{value1}',
  'Unable to clear the loyalty ledger.': 'ไม่สามารถล้างบัญชีสะสมแต้มได้',
  "Cleared all {value0} loyalty ledger entries. Every member's points and prepaid hours are now reset to zero.": 'ล้างรายการบัญชีสะสมแต้มทั้งหมด {value0} รายการแล้ว แต้มและชั่วโมงชำระล่วงหน้าของสมาชิกทุกคนเป็นศูนย์แล้ว',
  'Cleared {value0} ledger entr{value1} for {value2}. Their points and prepaid hours are now reset to zero.': 'ล้างรายการบัญชี {value0} รายการของ {value2} แล้ว แต้มและชั่วโมงชำระล่วงหน้าเป็นศูนย์แล้ว',
  'Unable to remove this company.': 'ไม่สามารถลบบริษัทนี้ได้',
  'Removed {value0} member(s) from {value1}.{value2}{value3}': 'ลบสมาชิก {value0} คนจาก {value1} แล้ว{value2}{value3}',
  '{value0} for {value1} copied to clipboard.': 'คัดลอก {value0} สำหรับ {value1} ไปยังคลิปบอร์ดแล้ว',
  '{value0} for {value1}: {value2}': '{value0} สำหรับ {value1}: {value2}',
  'Unable to save the business profile': 'ไม่สามารถบันทึกข้อมูลธุรกิจได้',
  'Unable to save therapists': 'ไม่สามารถบันทึกผู้ให้บริการได้',
  'Unable to load dashboard accounts.': 'ไม่สามารถโหลดบัญชีแผงควบคุมได้',
  'Unable to create dashboard account.': 'ไม่สามารถสร้างบัญชีแผงควบคุมได้',
  'Created {value0} access for {value1}. Share the initial password through a secure channel.': 'สร้างสิทธิ์ {value0} สำหรับ {value1} แล้ว กรุณาส่งรหัสผ่านเริ่มต้นผ่านช่องทางที่ปลอดภัย',
  'Unable to update dashboard account.': 'ไม่สามารถอัปเดตบัญชีแผงควบคุมได้',
  'Unable to load bookings from the database': 'ไม่สามารถโหลดการจองจากฐานข้อมูลได้',
  'Unable to delete booking': 'ไม่สามารถลบการจองได้',
  'Receipt {value0} was already emailed.': 'ส่งอีเมลใบเสร็จ {value0} ไปแล้ว',
  'Receipt {value0} was emailed to {value1}.': 'ส่งอีเมลใบเสร็จ {value0} ถึง {value1} แล้ว',
  'Unable to issue receipt': 'ไม่สามารถออกใบเสร็จได้',
  'This appointment was already marked as paid.': 'บันทึกนัดหมายนี้ว่าชำระแล้ว',
  'Payment of ${value0} recorded. You can now issue the receipt.': 'บันทึกการชำระ ${value0} แล้ว สามารถออกใบเสร็จได้',
  'Unable to record payment': 'ไม่สามารถบันทึกการชำระเงินได้',
  'Unable to load notes': 'ไม่สามารถโหลดหมายเหตุได้',
  'Unable to save note': 'ไม่สามารถบันทึกหมายเหตุได้',
  'Unable to save these booking details': 'ไม่สามารถบันทึกรายละเอียดการจองนี้ได้',
  'Reassigned from {value0} to {value1}.': 'เปลี่ยนผู้ให้บริการจาก {value0} เป็น {value1} แล้ว',
  'Unable to change the therapist for this appointment.': 'ไม่สามารถเปลี่ยนผู้ให้บริการสำหรับนัดหมายนี้ได้',
  'AI drafted a message for {value0} matching opted-in recipients. Review and edit it before saving or sending.': 'AI สร้างข้อความฉบับร่างสำหรับผู้รับที่ยินยอม {value0} คนแล้ว กรุณาตรวจสอบและแก้ไขก่อนบันทึกหรือส่ง',
  'Unable to generate a campaign draft': 'ไม่สามารถสร้างฉบับร่างแคมเปญได้',
  'Campaign sent to {value0} of {value1} opted-in recipients.{value2}': 'ส่งแคมเปญถึงผู้รับที่ยินยอม {value0} จาก {value1} คนแล้ว{value2}',
  'Unable to send campaign': 'ไม่สามารถส่งแคมเปญได้',
  'Unable to load campaign history': 'ไม่สามารถโหลดประวัติแคมเปญได้',
  'Unable to load Google Calendar events': 'ไม่สามารถโหลดกิจกรรม Google Calendar ได้',
  'Unable to load availability blocks': 'ไม่สามารถโหลดช่วงเวลาปิดรับจองได้',
  'Unable to save this block.': 'ไม่สามารถบันทึกช่วงเวลานี้ได้',
  'Unable to remove this block.': 'ไม่สามารถลบช่วงเวลานี้ได้',
  'Unable to load patient history': 'ไม่สามารถโหลดประวัติลูกค้าได้',
  'Unable to clear patient history record': 'ไม่สามารถล้างประวัติลูกค้าได้',
  'Unable to load therapist accounts': 'ไม่สามารถโหลดบัญชีผู้ให้บริการได้',
  'Unable to update therapist account': 'ไม่สามารถอัปเดตบัญชีผู้ให้บริการได้',
  'Thai Traditional': 'นวดแผนไทย',
  'Thai Combo Swedish': 'นวดไทยผสมสวีดิช',
  'Hot Stone Combo': 'นวดผสมหินร้อน',
  'Add-On & Packages': 'บริการเสริมและแพ็กเกจ',
  'RMT Healthcare': 'บริการสุขภาพ RMT',
  'Pay at clinic (no deposit)': 'ชำระที่คลินิก (ไม่มีมัดจำ)',
  'Pay in full online': 'ชำระเต็มจำนวนออนไลน์',
  'Members': 'สมาชิก',
  'Points outstanding': 'แต้มคงเหลือทั้งหมด',
  'Visits ready to award': 'บริการที่พร้อมให้แต้ม',
  'One member': 'สมาชิกหนึ่งคน',
  'Entire ledger': 'บัญชีทั้งหมด',
  'Ad spend': 'ค่าโฆษณา',
  'Describe with Gemini': 'อธิบายด้วย Gemini',
  'Manual filters': 'ตัวกรองด้วยตนเอง',
  'Customers who visit every Wednesday': 'ลูกค้าที่รับบริการทุกวันพุธ',
  'Legal name for receipts': 'ชื่อตามกฎหมายสำหรับใบเสร็จ',
  'Traditional Thai massage & wellness': 'นวดแผนไทยและสุขภาพ',
  'Optional — enter only your registered number': 'ไม่บังคับ — ใส่เฉพาะเลขทะเบียนของคุณ',
  'Your business': 'ธุรกิจของคุณ',
  'No therapist sign-ups are waiting for approval.': 'ไม่มีผู้ให้บริการที่รออนุมัติ',
  'No approved therapist accounts yet.': 'ยังไม่มีบัญชีผู้ให้บริการที่อนุมัติแล้ว',
  'Conditions flagged': 'ภาวะสุขภาพที่แจ้ง',
  'Pressure': 'น้ำหนักการนวด',
  'Not set': 'ยังไม่กำหนด',
  'Pain areas': 'บริเวณที่ปวด',
  'Recorded': 'บันทึกแล้ว',
  'Body areas': 'บริเวณร่างกาย',
  'Gross sales': 'ยอดขายรวม',
  'Balance outstanding': 'ยอดค้างชำระ',
  'No email on booking': 'ไม่มีอีเมลในการจอง',
  'Not provided': 'ไม่ระบุ',
  'Booking reference': 'เลขอ้างอิงการจอง',
  'Service date': 'วันที่รับบริการ',
  'Appointment time': 'เวลานัดหมาย',
  'Monday': 'วันจันทร์',
  'Tuesday': 'วันอังคาร',
  'Wednesday': 'วันพุธ',
  'Thursday': 'วันพฤหัสบดี',
  'Friday': 'วันศุกร์',
  'Saturday': 'วันเสาร์',
  'Sunday': 'วันอาทิตย์',
  'Standard': 'มาตรฐาน',
  'Platinum': 'แพลทินัม',
  'Silver': 'ซิลเวอร์',
  'active': 'ใช้งาน',
  'disabled': 'ระงับ',
  'owner': 'เจ้าของ',
  'branch manager': 'ผู้จัดการสาขา',
  'branch receptionist': 'พนักงานต้อนรับสาขา',
  'Confirmed': 'ยืนยันแล้ว',
  'Completed': 'เสร็จสิ้น',
  'No-show': 'ไม่มาตามนัด',
  'Light': 'เบา',
  'Medium': 'ปานกลาง',
  'Firm': 'หนัก',
  'Yes': 'ใช่',
  'No': 'ไม่',
  'Female': 'หญิง',
  'Male': 'ชาย',
  'Neutral': 'ไม่ระบุ',
  '3D body map': 'แผนภาพร่างกายสามมิติ',
  'Highlighted areas were reported by the patient. Drag the body or use the slider to turn it.': 'บริเวณที่เน้นคือตำแหน่งที่ลูกค้าแจ้ง ลากร่างกายหรือใช้แถบเลื่อนเพื่อหมุน',
  'Tap every affected area. Drag the body or use the slider to turn it.': 'เลือกทุกบริเวณที่มีอาการ ลากร่างกายหรือใช้แถบเลื่อนเพื่อหมุน',
  'Body type': 'รูปแบบร่างกาย',
  'marked': 'ตำแหน่งที่เลือก',
  'body': 'ร่างกาย',
  'Rotate body': 'หมุนร่างกาย',
  'Front': 'ด้านหน้า',
  'Right': 'ด้านขวา',
  'Back': 'ด้านหลัง',
  'Left': 'ด้านซ้าย',
  'R': 'ขวา',
  'L': 'ซ้าย',
  'Front-right': 'ด้านหน้าขวา',
  'Back-right': 'ด้านหลังขวา',
  'Back-left': 'ด้านหลังซ้าย',
  'Front-left': 'ด้านหน้าซ้าย',
  'Reported areas': 'บริเวณที่แจ้ง',
  'Affected areas': 'บริเวณที่มีอาการ',
  'No body areas were reported.': 'ไม่ได้แจ้งบริเวณร่างกาย',
  'Head / face': 'ศีรษะ / ใบหน้า',
  'Neck': 'คอ',
  'Shoulders': 'ไหล่',
  'Upper back': 'หลังส่วนบน',
  'Lower back': 'หลังส่วนล่าง',
  'Chest / abdomen': 'หน้าอก / หน้าท้อง',
  'Arms / hands': 'แขน / มือ',
  'Hips / glutes': 'สะโพก / ก้น',
  'Legs / knees': 'ขา / เข่า',
  'Feet': 'เท้า',
  'Heart Disease': 'โรคหัวใจ',
  'High/Low Blood Pressure': 'ความดันโลหิตสูง/ต่ำ',
  'Diabetes': 'เบาหวาน',
  'Cancer': 'มะเร็ง',
  'Headaches / Migraines': 'ปวดศีรษะ / ไมเกรน',
  'Bone/Joint Conditions': 'ภาวะกระดูก/ข้อต่อ',
  'Broken Bones': 'กระดูกหัก',
  'Osteoporosis': 'กระดูกพรุน',
  'Allergies': 'อาการแพ้',
  'Surgeries': 'การผ่าตัด',
  'Numbness': 'อาการชา',
  'Skin Sensitivity': 'ผิวไวต่อการสัมผัส',
  'Pregnant': 'ตั้งครรภ์',
  'Medications': 'ยา',
  'HST (13%)': 'ภาษี HST (13%)',
  'Tax exempt (regulated healthcare)': 'ยกเว้นภาษี (บริการสุขภาพที่กำกับดูแล)',
  'Tax exempt': 'ยกเว้นภาษี',
  'Membership discount': 'ส่วนลดสมาชิก',
  'Gold membership discount': 'ส่วนลดสมาชิก Gold',
  'Platinum membership discount': 'ส่วนลดสมาชิก Platinum',
  'clinic': 'ชำระที่คลินิก',
  'deposit': 'มัดจำ',
  'full': 'ชำระครบ',
  'cash': 'เงินสด',
  'card': 'บัตร',
  'e-transfer': 'โอนเงินอิเล็กทรอนิกส์',
  'other': 'อื่น ๆ',
  'Describe a group, or choose “All active opted-in subscribers” to include everyone. Branch, weekday, and recent-booking filters only match customers with corresponding booking history.': 'อธิบายกลุ่มผู้รับ หรือเลือก “ผู้รับอีเมลที่ยินยอมและใช้งานทุกคน” เพื่อรวมทุกคน ตัวกรองสาขา วัน และการจองล่าสุดตรงกับลูกค้าที่มีประวัติการจองเท่านั้น',
  'I could not build that audience. Try one of the example requests.': 'ไม่สามารถสร้างกลุ่มผู้รับได้ กรุณาลองใช้คำขอตัวอย่าง',
  'I could not build that audience from those filters.': 'ไม่สามารถสร้างกลุ่มผู้รับจากตัวกรองเหล่านั้นได้',
  'Employee signup link': 'ลิงก์ลงทะเบียนพนักงาน',
  'Company portal link': 'ลิงก์บริษัท',
  'check Gmail configuration.': 'ตรวจสอบการตั้งค่า Gmail',
  'check Gmail configuration and retry.': 'ตรวจสอบการตั้งค่า Gmail แล้วลองอีกครั้ง',
  ' Loyalty balance email sent.': ' ส่งอีเมลยอดสะสมแต้มแล้ว',
  ' Balance email sent.': ' ส่งอีเมลยอดคงเหลือแล้ว',
  ' Removal notice emailed.': ' ส่งอีเมลแจ้งการลบแล้ว',
  ' Confirmation emailed; the receipt number will be linked and emailed when the receipt is issued.': ' ส่งอีเมลยืนยันแล้ว เลขใบเสร็จจะเชื่อมและส่งทางอีเมลเมื่อออกใบเสร็จ',
  ' The company request is pending; use the member row to record the top-up after payment is confirmed.': ' คำขอบริษัทยังรอยืนยัน ใช้แถวสมาชิกบันทึกการเติมเงินหลังยืนยันการชำระ',
  ' A filter can exclude subscribers who do not have matching booking history. Choose “All active opted-in subscribers” to include everyone.': ' ตัวกรองอาจไม่รวมผู้รับที่ไม่มีประวัติการจองตรงกัน เลือก “ผู้รับอีเมลที่ยินยอมและใช้งานทุกคน” เพื่อรวมทุกคน',
  'Receipt': 'ใบเสร็จ',
  'RECEIPT': 'ใบเสร็จรับเงิน',
  'Receipt No.': 'เลขใบเสร็จ',
  'Issued': 'ออกเมื่อ',
  'Client': 'ลูกค้า',
  'Loyalty points balance:': 'แต้มสะสมคงเหลือ:',
  'Print receipt': 'พิมพ์ใบเสร็จ',
  'Thank you for choosing {business}.': 'ขอบคุณที่เลือก {business}',
  '{body} body diagram, {view} view, {areas}': 'แผนภาพร่างกาย {body} มุมมอง {view} {areas}',
  'marked areas: {areas}': 'บริเวณที่เลือก: {areas}',
  'no areas marked': 'ยังไม่ได้เลือกบริเวณ',
  '{area} (selected)': '{area} (เลือกแล้ว)',
  '{value0} (currency unavailable)': '{value0} (ไม่มีข้อมูลสกุลเงิน)',
  'heart': 'ภาวะหัวใจ',
  'bloodPressure': 'ความดันโลหิต',
  'diabetes': 'เบาหวาน',
  'cancer': 'มะเร็ง',
  'headaches': 'ปวดศีรษะ / ไมเกรน',
  'boneJoint': 'ภาวะกระดูกหรือข้อต่อ',
  'brokenBones': 'กระดูกหักหรืออุปกรณ์ฝังในร่างกาย',
  'osteoporosis': 'กระดูกพรุนหรือข้ออักเสบ',
  'allergies': 'แพ้น้ำมัน',
  'surgeries': 'การผ่าตัด',
  'numbness': 'อาการชาหรือสูญเสียความรู้สึก',
  'skinSensitivity': 'ผิวไวต่อการสัมผัสหรือช้ำง่าย',
  'pregnant': 'ตั้งครรภ์หรือเพิ่งคลอด',
  'medications': 'ยาหรืออาหารเสริม',
  'HST exempt': 'ยกเว้นภาษี HST',
  'Silver corporate discount': 'ส่วนลดสมาชิกบริษัท Silver',
  'Thai Traditional Massage ({minutes} min)': 'นวดแผนไทย ({minutes} นาที)',
  'Thai Traditional Massage - Couple ({minutes} min)': 'นวดแผนไทยสำหรับคู่ ({minutes} นาที)',
  'Thai Combination Swedish ({minutes} min)': 'นวดไทยผสมสวีดิช ({minutes} นาที)',
  'Thai Combination Swedish - Couple ({minutes} min)': 'นวดไทยผสมสวีดิชสำหรับคู่ ({minutes} นาที)',
  'Thai Combo Swedish + Hot Stone ({minutes} min)': 'นวดไทยผสมสวีดิชและหินร้อน ({minutes} นาที)',
  'Thai Combo Swedish + Hot Stone - Couple ({minutes} min)': 'นวดไทยผสมสวีดิชและหินร้อนสำหรับคู่ ({minutes} นาที)',
  'Hot Stone Add-On': 'บริการเสริมหินร้อน',
  'Package: {minutes} min x {sessions} Sessions': 'แพ็กเกจ: {minutes} นาที × {sessions} ครั้ง',
  'Registered Massage Therapy (RMT {minutes} min)': 'นวดบำบัดโดยผู้ขึ้นทะเบียน (RMT {minutes} นาที)',
  'Traditional Thai Acupuncture ({minutes} min)': 'ฝังเข็มแผนไทย ({minutes} นาที)',
  'Add appointment at {value0}': 'เพิ่มนัดหมายเวลา {value0}',
  'Remove {value0}': 'ลบ {value0}',
  'Remove tier {value0}': 'ลบระดับ {value0}',
  'service': 'บริการ',
  'branch': 'สาขา',
  "Patient's right side": 'ด้านขวาของลูกค้า',
  "Patient's left side": 'ด้านซ้ายของลูกค้า',
  'Sign out': 'ออกจากระบบ',
  'Verifying secure dashboard access…': 'กำลังตรวจสอบสิทธิ์แผงควบคุมอย่างปลอดภัย…',
  'Set up owner account': 'ตั้งค่าบัญชีเจ้าของ',
  'Dashboard sign in': 'เข้าสู่แผงควบคุม',
  'Create the first owner account using the one-time setup key from your administrator.': 'สร้างบัญชีเจ้าของแรกโดยใช้รหัสตั้งค่าใช้ครั้งเดียวจากผู้ดูแลระบบ',
  'Sign in with your account and verify using a code sent to your email.': 'เข้าสู่ระบบด้วยบัญชีและยืนยันด้วยรหัสที่ส่งไปยังอีเมล',
  'Owner name': 'ชื่อเจ้าของ',
  'Your name': 'ชื่อของคุณ',
  'Owner email': 'อีเมลเจ้าของ',
  'you@example.com': 'you@example.com',
  'name@example.com': 'name@example.com',
  'One-time setup key': 'รหัสตั้งค่าใช้ครั้งเดียว',
  'Owner password (at least 16 characters)': 'รหัสผ่านเจ้าของ (อย่างน้อย 16 ตัวอักษร)',
  'Confirm owner password': 'ยืนยันรหัสผ่านเจ้าของ',
  'Password': 'รหัสผ่าน',
  'Enter your password': 'ใส่รหัสผ่านของคุณ',
  'A six-digit verification code was sent to': 'ส่งรหัสยืนยัน 6 หลักไปยัง',
  'Email verification code': 'รหัสยืนยันทางอีเมล',
  'Back to email and password': 'กลับไปใส่อีเมลและรหัสผ่าน',
  'Please wait…': 'กรุณารอสักครู่…',
  'Create owner account': 'สร้างบัญชีเจ้าของ',
  'Verify and sign in': 'ยืนยันและเข้าสู่ระบบ',
  'Continue to email verification': 'ดำเนินการต่อเพื่อยืนยันอีเมล',
  'Return to dashboard sign in': 'กลับไปเข้าสู่แผงควบคุม',
  'First time here? Set up the owner account': 'ใช้งานครั้งแรก? ตั้งค่าบัญชีเจ้าของ',
  'Setup closes automatically after the first owner account is created.': 'การตั้งค่าจะปิดโดยอัตโนมัติหลังสร้างบัญชีเจ้าของแรก',
  'Your secure session expires after 8 hours.': 'เซสชันที่ปลอดภัยของคุณหมดอายุหลัง 8 ชั่วโมง',
  'Owner sign-in is unavailable.': 'ไม่สามารถเข้าสู่ระบบเจ้าของได้',
  'Unable to verify owner session.': 'ไม่สามารถตรวจสอบเซสชันเจ้าของได้',
  'Unable to sign out.': 'ไม่สามารถออกจากระบบได้',
  'Unable to sign in.': 'ไม่สามารถเข้าสู่ระบบได้',
  '$10 deposit': 'มัดจำ $10',
  'enabled': 'เปิดใช้งาน',
  'paused': 'หยุดชั่วคราว',
  'removed': 'ลบแล้ว',
  'Most recent customers at {branch} in the last 30 days': 'ลูกค้าล่าสุดที่ {branch} ในช่วง 30 วันที่ผ่านมา',
  'All opted-in customers at {branch}': 'ลูกค้าที่ยินยอมรับอีเมลทุกคนที่ {branch}',
  'Enter a non-negative manual discount in dollars, with at most two decimal places.': 'กรุณาใส่ส่วนลดเป็นดอลลาร์ที่ไม่ติดลบ และมีทศนิยมไม่เกินสองตำแหน่ง',
  'This receipt has already been created. Its manual discount cannot be changed.': 'สร้างใบเสร็จนี้แล้ว ไม่สามารถเปลี่ยนส่วนลดได้',
  'Confirm reconciliation of the discounted payment before issuing this receipt.': 'กรุณายืนยันการกระทบยอดการชำระหลังส่วนลดก่อนออกใบเสร็จนี้',
  'Manual discounts cannot change a verified prepaid package allocation.': 'ส่วนลดที่พนักงานกำหนดไม่สามารถเปลี่ยนการจัดสรรแพ็กเกจชำระล่วงหน้าที่ตรวจสอบแล้ว',
  'The manual discount cannot exceed the subtotal remaining after membership and loyalty discounts.': 'ส่วนลดต้องไม่เกินยอดก่อนภาษีคงเหลือหลังหักส่วนลดสมาชิกและสะสมแต้ม',
  'Dashboard sign-in required': 'กรุณาเข้าสู่แผงควบคุม',
  'Request origin is not allowed': 'ไม่อนุญาตคำขอจากแหล่งนี้',
  'A valid booking ID is required.': 'ต้องระบุรหัสการจองที่ถูกต้อง',
  'Enter an internal booking note, or leave it empty to clear it.': 'ใส่หมายเหตุภายใน หรือเว้นว่างเพื่อล้างหมายเหตุ',
  'Refresh the booking note before saving.': 'กรุณารีเฟรชหมายเหตุการจองก่อนบันทึก',
  'Booking was not found.': 'ไม่พบการจอง',
  'This booking is outside your assigned branch access.': 'การจองนี้อยู่นอกสาขาที่คุณได้รับสิทธิ์',
  'The booking note changed. Refresh the appointment before saving.': 'หมายเหตุการจองเปลี่ยนแล้ว กรุณารีเฟรชนัดหมายก่อนบันทึก',
  'Enter an internal booking note of no more than 2,000 characters.': 'ใส่หมายเหตุภายในไม่เกิน 2,000 ตัวอักษร',
  'Add GEMINI_API_KEY to Vercel Environment Variables and redeploy to enable Gemini audience matching. Keyword matching is used until then.': 'เพิ่ม GEMINI_API_KEY ในตัวแปรสภาพแวดล้อม Vercel และปรับใช้ใหม่เพื่อเปิดการเลือกกลุ่มผู้รับด้วย Gemini ระหว่างนี้จะใช้การจับคู่คำสำคัญ',
  'Add GEMINI_API_KEY to Vercel Environment Variables and redeploy to enable AI campaign writing.': 'เพิ่ม GEMINI_API_KEY ในตัวแปรสภาพแวดล้อม Vercel และปรับใช้ใหม่เพื่อเปิดการเขียนแคมเปญด้วย AI',
  '{value0} points awarded to {value1}': 'ให้ {value0} แต้มแก่ {value1}',
  "{value0}'s visit recorded": 'บันทึกการรับบริการของ {value0} แล้ว',
  '; {value0} prepaid hours used.': ' ใช้ชั่วโมงชำระล่วงหน้า {value0} ชั่วโมง',
  ' Balance email failed: {value0}': ' ส่งอีเมลยอดคงเหลือไม่สำเร็จ: {value0}',
  '{value0}{value1}{value2}': '{value0}{value1}{value2}',
  ' Redemption saved, but confirmation email failed: {value0}': ' บันทึกการแลกแต้มแล้ว แต่ส่งอีเมลยืนยันไม่สำเร็จ: {value0}',
  ' {value0} prepaid hours were added after confirming payment.': ' เพิ่มชั่วโมงชำระล่วงหน้า {value0} ชั่วโมงหลังยืนยันการชำระเงินแล้ว',
  'Membership saved and eligibility details emailed to {value0}.': 'บันทึกสมาชิกและส่งรายละเอียดสิทธิ์ถึง {value0} ทางอีเมลแล้ว',
  'Membership saved, but the email could not be sent: {value0}': 'บันทึกสมาชิกแล้ว แต่ส่งอีเมลไม่สำเร็จ: {value0}',
  '{value0}{value1}': '{value0}{value1}',
  ' {value0} payment notification(s) failed.': ' ส่งการแจ้งชำระเงิน {value0} ฉบับไม่สำเร็จ',
  ' Payment confirmations emailed to {value0} member(s).': ' ส่งอีเมลยืนยันการชำระเงินให้สมาชิก {value0} คนแล้ว',
  ' Removal notice failed: {value0}': ' ส่งการแจ้งลบไม่สำเร็จ: {value0}',
  'y': 'y',
  'ies': 'ies',
  ' {value0} removal notice(s) emailed.': ' ส่งอีเมลแจ้งลบ {value0} ฉบับแล้ว',
  ' {value0} notice(s) failed.': ' ส่งการแจ้ง {value0} ฉบับไม่สำเร็จ',
  'person': 'คน',
  'people': 'คน',
  ' {value0}': ' {value0}',
  '{value0} I found {value1} matching {value2} from {value3} active opted-in subscribers.{value4}': '{value0} พบผู้รับที่ตรงกัน {value1} {value2} จากผู้สมัครรับอีเมลที่ยินยอมและใช้งาน {value3} คน{value4}',
  '{value0} I found {value1} matching {value2} from {value3} active opted-in subscribers.{value4}{value5}': '{value0} พบผู้รับที่ตรงกัน {value1} {value2} จากผู้สมัครรับอีเมลที่ยินยอมและใช้งาน {value3} คน{value4}{value5}',
  ' {value0} message{value1} failed; check server logs before retrying to avoid duplicate emails.': ' ส่งข้อความ {value0} ฉบับไม่สำเร็จ กรุณาตรวจสอบบันทึกเซิร์ฟเวอร์ก่อนลองอีกครั้งเพื่อเลี่ยงอีเมลซ้ำ',
  'Campaign delivery finished: {value0} sent and {value1} failed.': 'ส่งแคมเปญเสร็จแล้ว: ส่งสำเร็จ {value0} ฉบับ และไม่สำเร็จ {value1} ฉบับ',
  'Allocated session value ${value}; new payment $0.00.': 'มูลค่าบริการที่จัดสรร ${value}; การชำระใหม่ $0.00',
  '{packageName} ({packageId}, purchase {purchaseReference}): 1 session deducted; {remaining} of 4 sessions remain after this visit. Covered by prepayment; no new payment collected.': '{packageName} ({packageId}, การซื้อ {purchaseReference}): หัก 1 ครั้ง เหลือ {remaining} จาก 4 ครั้งหลังบริการนี้ ครอบคลุมโดยการชำระล่วงหน้า ไม่มีการรับชำระใหม่',
};
